// LAST GAME IS meat on the move (one-html-page-challenge batch)
let files = [
  "altsingle",
  "cl1",
  "cl100in1nes",
  "cl100RoomsOfEnemies",
  "cl10bullets",
  "cl10minutestildawn",
  "cl10morebullets",
  "cl10yardfight",
  "cl12minibattles",
  "cl13bones",
  "cl1942nes",
  "cl1on1soccer",
  "cl1v1lol",
  "cl1v1tennis",
  "cl2048",
  "cl2048cupcakes",
  "cl20smallmazes",
  "cl234playergame",
  "cl2doom",
  "cl2Dshooting",
  "cl2dsitesnacker",
  "cl3dash",
  "cl3dasheditor",
  "cl3dpinballspacecadet",
  "cl3pandas",
  "cl3pandasbrazil",
  "cl3pandasfantasy",
  "cl3pandasjapan",
  "cl3pandasnight",
  "cl3slices2",
  "cl40xescape",
  "cl4thandgoal",
  "cl500calibercontractz",
  "cl60secondsburgerrun",
  "cl60secondssantarun",
  "cl64in1nes",
  "cl8ballclassic",
  "cl8ballpool",
  "cl9007199254740992",
  "cl90in1nes",
  "cl99balls",
  "cl99nightsitf",
  "clA Walk in The Forest (v10)",
  "clabandoned3",
  "clabsolutemadness",
  "claceattorneymilesedgeworth",
  "clacecombat2",
  "clacecombat3",
  "clacegangstertaxi",
  "clachievementunlocked",
  "clachievmentunlocked",
  "clachievmentunlocked2",
  "clachievmentunlocked3",
  "clachillies",
  "clachillies2",
  "clAcko_s Mach Bike Challenge (v10)",
  "clADarkRoom",
  "cladatewithdeath",
  "cladayintheoffice",
  "cladjustablefireworks",
  "clADOFAI",
  "cladvancewars",
  "cladvancewars2",
  "cladvancewarsdualstrike",
  "cladventneon",
  "clAdventureCapatalist",
  "cladventurecapitalist",
  "claffirmationgenerator",
  "claflac",
  "claftertheweek",
  "clagariolite",
  "clageofwar",
  "clageofwar2",
  "clagesofconflict",
  "clagesofempire",
  "clahoysurvival",
  "clai",
  "claimclickchallenge",
  "clairlinetycoonidle",
  "clakoopasrevenge",
  "clakoopasrevenge2",
  "clakumanorgaiden",
  "claladdinsnes",
  "clalexkiddinmiracleworld",
  "clalienhominid",
  "clalienhominidgba",
  "clalienskyinvasion",
  "clalientransporter",
  "clalienvspredator",
  "clallbossesin1",
  "clallocation",
  "clAltered Beast",
  "clamaze",
  "clambulencearush",
  "clamidstthesky",
  "clamigopancho",
  "clamigopancho2",
  "clamigopancho3",
  "clamigopancho4",
  "clamigopancho5",
  "clamigopancho6",
  "clamigopancho7",
  "clamongus",
  "clamorphous",
  "clancientsins",
  "clanemonesfall",
  "clangry-birdsspace",
  "clangrybirds",
  "clangrybirds-space",
  "clangrybirds2",
  "clangrybirdsshowdown",
  "clangrybirdsslingshotfrenzy",
  "clangrybirdsspace",
  "clanimalcrossing",
  "clanimalcrossingwildworld",
  "clanimalforestn64",
  "clannsmb",
  "clanotherworld",
  "clantarttycoon",
  "clantcolony",
  "clantimatterdimensions",
  "clantipathy",
  "clapesvshelium",
  "clapotris",
  "clappleshooter",
  "clappleworm",
  "claquaparkio",
  "clarcadevolley",
  "clarceuslegend",
  "clarcheryworldtour",
  "clarchesspelago",
  "clarena",
  "clarmormayhem2",
  "clarsonate",
  "clarthursnightmare",
  "clartist1p",
  "clascent",
  "clasciicam",
  "clasdutydemands",
  "clasmallworldcup",
  "classesmentexaminationque",
  "classessmentexamination",
  "clasteroids",
  "clasteroidsALT",
  "clasteroidsarcade",
  "clastray",
  "clAstrosDreamland",
  "clastynax",
  "clatariadventure",
  "clatributepage",
  "clattackhole",
  "clavalanche",
  "claviamasters",
  "claviamastersbuggy",
  "clavoidthebikes",
  "clAwesomePirates",
  "clawesomeplanes",
  "clawesometanks",
  "clawesometanks2",
  "claxbattler",
  "claxisfootballleague",
  "clB3313",
  "clb3313unabandonedA2",
  "clb3313v102",
  "clbabeltower",
  "clbabychiccoadventure",
  "clbabykaizo",
  "clbabysniperinvietnam",
  "clbabywantsmilk",
  "clbackgroundlight",
  "clbackrooms",
  "clbackrooms2D",
  "clbackyardbaseball",
  "clbackyardbaseball09",
  "clbackyardbaseball10",
  "clbackyardfootball",
  "clbackyardsoccer",
  "clbaconmaydie",
  "clbadbodyguards",
  "clbadicecream",
  "clbadicecream2",
  "clbadicecream3",
  "clbadmondaysimulator",
  "clbadparenting",
  "clbadpiggies",
  "clbadpiggieslatest",
  "clbadtimesim",
  "clbadtimesimulator",
  "clbalatrogba",
  "clbaldi-3",
  "clbaldi-b",
  "clbaldicaseoh",
  "clbaldidecomp",
  "clbaldiepstein",
  "clbaldisbasics",
  "clbaldisbasicsremaster",
  "clbaldisfunnewschoolultimate",
  "clballblast",
  "clballistic",
  "clballoonfight",
  "clballsandbricks",
  "clballsandbricksgood",
  "clballz",
  "clbananasimulator",
  "clbanbuds",
  "clbanditgunslingers",
  "clbanjokazooie",
  "clbanjotooie",
  "clBank Robbery",
  "clbankbreakout2",
  "clbankrobbery2",
  "clbarryhasasecret",
  "clbartblast",
  "clbas",
  "clbase64totxt",
  "clbaseballbros",
  "clbaseballnes",
  "clbasketballfrvr",
  "clbasketballlegends",
  "clbasketballlegends(1)",
  "clbasketballstars",
  "clbasketballsuperstars",
  "clbasketbattle",
  "clbasketbros",
  "clbasketrandom",
  "clbasketrandomgood",
  "clbasketslamdunk2",
  "clbatterup",
  "clbattlekarts",
  "clbattles",
  "clbattlesim",
  "clbattlezone",
  "clbazookaboy",
  "clbballlegend",
  "clbeachboxingsim",
  "clbeamrider",
  "clbearbarians",
  "clbearsus",
  "clbejeweledtwistds",
  "clbejeweledtwistflash",
  "clben10alienforce",
  "clben10omniverse",
  "clben10protector",
  "clben10racing",
  "clben10ultimatealien",
  "clbendrowned",
  "clbergentruck201x",
  "clbfdia5b",
  "clBFDIBranches",
  "clBig_Time_Butter_Baron",
  "clbigflappytowertinysquare",
  "clbigicetowertinysquare",
  "clbigneontowertinysquare",
  "clbigshotboxing2",
  "clbigtowertinysquare",
  "clbigtowertinysquare2",
  "clbigtowertinysquare2good",
  "clbindingofisaccsheeptime",
  "clbioevil4",
  "clbirthdaycake",
  "clbitburner",
  "clbitlife",
  "clbitlifeencrypted",
  "clbitplanes",
  "clbitsrain",
  "clblackjack",
  "clblackjackbattle",
  "clblackjackhhhh",
  "clblackknight",
  "clblackout",
  "clblacksmithlab",
  "clblastronaut",
  "clblazedrifter",
  "clbleachvsnaruto",
  "clblightborne",
  "clblobsstory2",
  "clblockblast",
  "clblockblastv2",
  "clblockcraftparkour",
  "clblockcraftshooter",
  "clblockoverit",
  "clblockpost",
  "clblockthepig",
  "clblockydemolitionderby",
  "clblockysnakes",
  "clblood",
  "clbloodmoney",
  "clbloodtournament",
  "clbloons",
  "clbloons2",
  "clbloonspp1",
  "clbloonspp2",
  "clbloonspp3",
  "clbloonspp4",
  "clbloonspp5",
  "clbloonsTD1",
  "clbloonsTD2",
  "clbloonsTD3",
  "clbloonsTD4",
  "clbloonsTD5",
  "clbloonsTD6scratch",
  "clbloxorz",
  "clblumgiracers",
  "clblumgirocket",
  "clblurloadingpage",
  "clbmicalculator",
  "clBMX2",
  "clbntts",
  "clbobasimulator",
  "clbobtherobber",
  "clbobtherobber2",
  "clbobtherobber5",
  "clbollybeat",
  "clbomberman",
  "clbomberman2",
  "clbombermanhero",
  "clbombermanworld",
  "clBonanza-Bros",
  "clbonkerssnes",
  "clboomslingers",
  "clbotblitz",
  "clbottlecracks",
  "clbottleflip3d",
  "clbotwds",
  "clbounceback",
  "clbouncemasters",
  "clbouncybasketball",
  "clbouncymotors",
  "clBountyOfOne",
  "clbowlalt",
  "clbowmaster",
  "clboxhead2playrooms",
  "clboxheadnightmare",
  "clboxinglive-2",
  "clboxinglive2",
  "clboxingrandom",
  "clbrainrot",
  "clbrawlsimulator3d",
  "clBrawlstars",
  "clbreadskate",
  "clbridgerace",
  "clbrotato",
  "clBTD1",
  "clbtd5",
  "clbtts",
  "clbtts2",
  "clbubbleshooter",
  "clbubbleshooterpirate",
  "clbubbletanks",
  "clbubbletanks2",
  "clbubbletanks3",
  "clbubbletanksarenas",
  "clbubbletankstd",
  "clbubsy",
  "clbuckbumble",
  "clbuckshotroulette",
  "clbuilding",
  "clbuildnowgg",
  "clbulletforce",
  "clbunnyland",
  "clbunzobunny",
  "clburgerandfrights",
  "clburgertime",
  "clburritobison",
  "clburritobison2",
  "clburritobisonlaunchalibre",
  "clburritobisonrevenge",
  "clbushidoblade",
  "clBusterJam",
  "clbuttonhover",
  "clcactusmccoy",
  "clcactusmccoy(1)",
  "clcactusmccoy2",
  "clcactusmccoy2(1)",
  "clcactusmccoy2(2)",
  "clcalculatehoursworked",
  "clcalculator",
  "clcalendar",
  "clcallofbattle",
  "clcamilla",
  "clcandybox1",
  "clcannonballs3d",
  "clcannonfodder",
  "clcaptainlang",
  "clcaptchaware",
  "clcapybaraclicker",
  "clcarcrash3",
  "clcardrawing",
  "clcareatscar2deluxe",
  "clcarkingarena",
  "clcarmods",
  "clcarnivalgamesds",
  "clcarrampvspolicechase",
  "clcarstuntsdriving",
  "clCartoonNetworkTableTennisUltimateTournament",
  "clcastaway",
  "clcastlebloodline",
  "clcastlecircleofmoon",
  "clcastlevania",
  "clcastlevania2",
  "clcastlevania3",
  "clcastlevaniaariaofsorrow",
  "clcastlevaniadawnofsorrow",
  "clcastlevanianes",
  "clcastlewarsmodern",
  "clcatmario",
  "clcatmariogood",
  "clcatslovecake2",
  "clcavecrawler",
  "clcavestory",
  "clceleste",
  "clceleste2",
  "clcelestemariodx",
  "clCeliasStupidROMHack",
  "clcellardoor",
  "clCellToSingularity",
  "clcentipedearcade",
  "clchainofmemories",
  "clchaosfaction2",
  "clchaosinonepage",
  "clcheckers",
  "clcheesechompers3d",
  "clcheeseisthereason",
  "clcheeserolling",
  "clcheshireinachatroom",
  "clchess",
  "clchessclassic",
  "clchibiknight",
  "clChickenCS",
  "clchickenscream",
  "clchickenwar",
  "clchipschallenge",
  "clchoppyorc",
  "clchoroqwonderful",
  "clchronotrigger",
  "clchuzzle",
  "clCircloO2",
  "clciviballs",
  "clciviballs2",
  "clclashnslash",
  "clclashofvikings",
  "clclassof09",
  "clclaymore",
  "clclayuncraft",
  "clcleanupio",
  "clclearvision",
  "clclearvision2",
  "clclearvision3",
  "clclearvision4",
  "clclearvision5",
  "clclimbforbrainrots",
  "clclmadnessambulation",
  "clclock",
  "clclover",
  "clclubbytheseal",
  "clclucluland",
  "clclumsybird",
  "clclusterrush",
  "clcoalllcdemo",
  "clcod4",
  "clcodblackopp",
  "clcoddefiance",
  "clcodenamegordon",
  "clcodeorg",
  "clcodeorgbutoffline",
  "clcodercraft",
  "clcodmodernwarfare",
  "clcodworldatwar",
  "clcoffeemaker",
  "clcoldfront",
  "clcoldpines",
  "clcolorburst3d",
  "clcolorchangeonhoverobjects",
  "clcolorclock",
  "clcolorgrid",
  "clcolormatch",
  "clcolorquiz",
  "clcolorwatersort3d",
  "clcombopool",
  "clcommandandconquer",
  "clcommanderkeen4",
  "clcommanderkeen5",
  "clcommanderkeen6",
  "clconfrontingurself",
  "clconfrontingyourself",
  "clconkersbadfurday",
  "clcontactlist",
  "clcontra",
  "clcontra3",
  "clcookie-clicker",
  "clcookieclicker",
  "clcookieclickercool",
  "clcookieclickergood",
  "clcookieclickermodmenu",
  "clcookingmama",
  "clcookingmama2",
  "clcookingmama3",
  "clcoreball",
  "clcoronaparty",
  "clcoryinthehouse",
  "clcotlk",
  "clcountmastersstickmangames",
  "clcoverorange",
  "clcoverorange2",
  "clcoverorangejourneygangsters",
  "clcoverorangejourneyknights",
  "clcoverorangejourneypirates",
  "clcoverorangejourneyspace",
  "clcoverorangeplayerspack",
  "clcoverorangeplayerspack2",
  "clcoverorangeplayerspack3",
  "clcoverorangeplayerspack3(1)",
  "clcrankit",
  "clcrankit!",
  "clcrash2",
  "clcrash3",
  "clcrashbandicoot",
  "clcrashbandicoot (1)",
  "clcrashbandicoot2",
  "clcrashbash",
  "clcrashteamracing",
  "clcrazycars",
  "clcrazycattle3d",
  "clcrazychicken3D",
  "clcrazyclimber",
  "clcrazyfrogracer",
  "clcrazymotorcycle",
  "clcrazypenguincatapult",
  "clcrazyplanelanding",
  "clcrazytaxigba",
  "clcreaturecardidle",
  "clcreeperworld2",
  "clcreepyinternetstories",
  "clcreepynightfunkin",
  "clcrimsonmadness",
  "clcrossyroad",
  "clcrunchball3000",
  "clCrystalCastles",
  "clcs16",
  "clcs6",
  "clcsds",
  "clcsgoclicker",
  "clcsscalc",
  "clctgpnitro",
  "clcupwaterwave",
  "clcurveball",
  "clcurveball(1)",
  "clcustomersupport",
  "clcuttherope",
  "clcuttheropeholiday",
  "clcuttheropetimetravel",
  "clcvooc",
  "clcyberbungracing",
  "clcybersensation",
  "cldadgame",
  "cldadish",
  "cldadnme",
  "cldaggerfall",
  "cldancingman",
  "cldandysworldclicker",
  "cldanktomb",
  "cldasharena",
  "cldashio",
  "clDashmetry",
  "cldatemeform",
  "cldatewithiraq",
  "cldborigins",
  "cldborigins2",
  "cldbsniper",
  "cldbzattacksaiyans",
  "cldbzdevolution",
  "cldbzsuperwarriorssonic",
  "cldbzwarriors2",
  "clddlc64",
  "cldeadair",
  "cldeadestate",
  "cldeadfrontieroutbreak",
  "cldeadfrontieroutbreak2",
  "cldeadlydescent",
  "cldeadplate",
  "cldeadseat",
  "cldeadzed",
  "cldeadzed2",
  "cldeathchase",
  "cldeathrun",
  "cldeblob2",
  "cldecision",
  "cldecision2",
  "cldecision3",
  "cldecisionmedieval",
  "cldeepersleep",
  "cldeepestsword",
  "cldeepsleep",
  "cldefenderarcade",
  "cldefendyourcastle",
  "cldefendyournuts",
  "cldefendyournuts2",
  "cldeltarune",
  "cldeltatraveler",
  "cldementium",
  "cldemolitionderbycrashracing",
  "cldemonblade",
  "cldemonbluff",
  "cldiablo",
  "cldiamondhollow",
  "cldiamondhollow2",
  "cldiddykong-racing",
  "cldieinthedungeon",
  "cldigdeep",
  "cldigdug",
  "cldigdug2",
  "cldigdug26",
  "cldigitalclock",
  "clDigOutofPrison",
  "cldigtochina",
  "cldimensionalincident",
  "cldinodudes",
  "cldinorun",
  "cldinorunenterplanetd",
  "cldinorunmarathonofdoom",
  "cldiredecks",
  "cldkccompetitioncart",
  "clDKNESCollection",
  "clDKNESCollection(1)",
  "cldoblox",
  "cldodecadragons",
  "cldogeminer",
  "cldogeminer2",
  "cldokidokiliteratureclub",
  "cldomeromantik",
  "cldonkeykong",
  "cldonkeykong64",
  "cldonkeykong94",
  "cldonkeykongcountry",
  "cldonkeykongcountry2",
  "cldonkeykongcountry3",
  "cldonkeykongnes",
  "cldontescape",
  "cldontescape2",
  "cldontescape3",
  "cldontyoulecturemehtml",
  "cldoodlejump",
  "cldoodlejumpgoober",
  "cldoom",
  "cldoom2",
  "cldoom2d",
  "cldoom2dDOS",
  "cldoom2dos",
  "cldoom3pack",
  "cldoom64",
  "cldoomdos",
  "cldoomemscripten",
  "cldoomori",
  "cldoomps",
  "cldoompsalt",
  "cldoomzio",
  "cldoorscastle",
  "cldoswasmx",
  "cldoubledribble",
  "cldouchebaglife",
  "cldouchebagworkout",
  "cldouchebagworkout2",
  "cldownthemountain",
  "cldragonballadvance",
  "clDragonBallZTheLegacyofGoku",
  "cldragonquest5ds",
  "clDragonQuestIX",
  "cldragonwarriormonsters",
  "clDragonxclient",
  "cldrawclimber",
  "cldrawntolife",
  "cldrawntolife2",
  "cldrawrgb",
  "cldrawtheline",
  "cldreader",
  "cldreadheadparkour",
  "cldriftboss",
  "cldrifthuntersmerge",
  "cldriftsimulator",
  "cldrivemad",
  "cldrivemady",
  "cldrivenwild",
  "cldriverussia",
  "cldrmario",
  "cldrweedgaster",
  "cldta6",
  "cldubstep",
  "clduckhunt",
  "clducklfe5",
  "clducklife",
  "clducklife2",
  "clducklife3",
  "clducklife4",
  "clducklifebattle",
  "clducklifespace",
  "clducklingsio",
  "clducktales",
  "clducktales2",
  "cldud",
  "cldukenukem2",
  "cldukenukem3d",
  "cldumbwaystodie",
  "cldumpling",
  "cldunebuggy",
  "cldunedash",
  "cldungeondeck",
  "cldungeonraid",
  "cldungeonsanddegenerategambler",
  "cldungeonsanddegenerategamblerdebug",
  "cldungeonsanddegenerategamblers",
  "cldunkshot",
  "clduskchild",
  "cldyingdreams",
  "cldynamiteheaddy",
  "clEaglercraft-Alpha-126-Offline",
  "clEaglercraft-Beta-1.3-Offline.html",
  "clEaglercraft-Beta-13-Offline",
  "clEaglercraft-Beta-1.3-Offline",
  "clEaglercraft-Indev-Offline",
  "clEaglercraft-Indev-Offline (1)",
  "clEaglercraft-Indev-Offline(1)",
  "clEaglercraft-Indev-Offline(2)",
  "cleaglercraft152",
  "clEaglercraftL_19_v0_7_0_Offline_Signed",
  "clEaglercraftL_19_v0_7_0_Offline_Signed(1)",
  "cleaglercraftnebula",
  "cleagleride",
  "clearntodie",
  "clearntodie2",
  "clearthbound",
  "clearthbound3",
  "clearthboundsnes",
  "clearthtaken",
  "clearthtaken2",
  "clearthtaken3",
  "clearthwormgg",
  "clearthwormjim",
  "clearthwormjim (1)",
  "clearthwormjim2",
  "clearthwormjim2 (1)",
  "cleccothedolphin",
  "cledelweiss",
  "cledyscarsimulator",
  "cleffinghail",
  "cleffingmachines",
  "cleffingworms",
  "cleffingzombies",
  "clegg",
  "cleggycar",
  "clelasticface",
  "clelectricman2",
  "clelevatoraction",
  "clelytraflight",
  "clemujs",
  "clenchain",
  "clendacopia",
  "clendlesswar4",
  "clendlesswar5",
  "clendlesswar5wow",
  "clendlesswar7",
  "clenduro",
  "clepicbattlefantasy5",
  "clescalatingduel",
  "clescaperoad",
  "clescaperoad-2",
  "clescaperoad3",
  "clescaperoadcity2",
  "clescapeschoolduel",
  "clet",
  "cletrianoddyssey",
  "cleugeneslife",
  "cleurovisionsim",
  "clevilglitch",
  "clevolution",
  "clexcitebike",
  "clexcitebike64",
  "clexitpath",
  "clexoobservation",
  "clextremerun3d",
  "clfactoryballs",
  "clfactoryballs2",
  "clfactoryballs3",
  "clfactoryballs4",
  "clfairytalevsonepiece",
  "clfallgame",
  "clfallguys",
  "clfallout",
  "clfamidash",
  "clfamidash128",
  "clfamidash2alpha",
  "clfamidashAlbum128",
  "clfamidashBSides128",
  "clfamidashCSides128",
  "clfamidashDSides128",
  "clfamidashESides1.2.8.html",
  "clfamilyguycorrupted",
  "clfancypantsadventure",
  "clfancypantsadventure2",
  "clfancypantsadventure3",
  "clfancysnowboarding",
  "clfantasyzone",
  "clfashionbattle",
  "clfattygenius",
  "clfearassessment",
  "clfearstofathomhomealone",
  "clfeedthevoid",
  "clfeedus",
  "clfeedus2",
  "clfeedus3",
  "clfeedus4",
  "clfeedus5",
  "clff2ws",
  "clFF3",
  "clff6",
  "clffaf",
  "clffmysticquest",
  "clFFsonic1",
  "clFFsonic2",
  "clFFsonic3",
  "clFFsonic4",
  "clFFsonic5",
  "clFFsonic61",
  "clFFsonic62",
  "clFIFA07",
  "clFIFA10",
  "clFIFA11",
  "clfifa2000",
  "clFIFA2000(1)",
  "clFIFA2000(2)",
  "clFIFA99",
  "clFIFAinternationalsoccer",
  "clFIFAroadtoworldcup98",
  "clFIFAsoccer06",
  "clFIFAsoccer95",
  "clFIFAsoccer96",
  "clFIFAsoccer97",
  "clFIFAstreet2",
  "clfinalearth2",
  "clfinalfantasy",
  "clfinalfantasy2nes",
  "clfinalfantasy3nes",
  "clfinalfantasyII",
  "clfinalfantasyIX",
  "clfinalfantasylegend2",
  "clfinalfantasytactics",
  "clfinalfantasyVI",
  "clfinalfantasyVII",
  "clfinalfantasyVIId2",
  "clfinalfantasyVIId3",
  "clfinalfantasyVIItheothertetrr",
  "clfinalninja",
  "clfindthealien",
  "clfireblob",
  "clfireboyandwatergirl",
  "clfireboyandwatergirl2",
  "clfireboyandwatergirl3",
  "clfireboyandwatergirl5",
  "clfireboyandwatergirl6",
  "clfireemblem",
  "clfireworks",
  "clfisheatgettingbig",
  "clfishies",
  "clfisquarium",
  "clfivenightsatbaldisredone",
  "clfivenightsatepsteins",
  "clfivenightsatfrickbears3",
  "clfivenightsatshreks",
  "clfivenightsatshrekshotel",
  "clfivenightsatyoshis",
  "clflames",
  "clflappybird",
  "clflashsonic",
  "clFleurdeLis",
  "clfloodrunner",
  "clfloodrunner2",
  "clfloodrunner3",
  "clfloodrunner4",
  "clfluidism",
  "clfnac1",
  "clfnac2",
  "clFNAF",
  "clFNAF2",
  "clFNAF3",
  "clfnaf3remastered",
  "clFNAF4",
  "clfnaf4halloween",
  "clfnafanimatronics",
  "clfnafps",
  "clfnafshooter",
  "clfnafsl",
  "clfnafucn",
  "clfnafworldd",
  "clfnaw",
  "clfnfaethos",
  "clfnfagoti",
  "clfnfakage",
  "clfnfanimation",
  "clfnfannie",
  "clfnfasdf",
  "clfnfbelowdepths",
  "clfnfbfdi26",
  "clfnfbinarybreakdown",
  "clfnfblackbetrayal",
  "clfnfbside",
  "clfnfcamelliarudeblaster",
  "clfnfcandycarrier",
  "clfnfchara",
  "clfnfcitytales",
  "clfnfclassified",
  "clfnfcorrosion",
  "clfnfcory",
  "clfnfcrunchin",
  "clfnfdeciever",
  "clfnfdesolation",
  "clfnfdocumictxtv3",
  "clfnfdokitakeoverplus",
  "clfnfdropandroll",
  "clfnfdsides",
  "clfnfdustin",
  "clfnfdusttale",
  "clfnffleetway",
  "clfnfflippedout",
  "clfnffnaf1",
  "clfnffnaf2",
  "clfnffnaf3",
  "clfnffnatpt",
  "clfnfgamebreakerbundle",
  "clfnfgfmode",
  "clfnfgodot",
  "clfnfgoldenapple",
  "clfnfhank",
  "clfnfheartbreakhavoc",
  "clfnfherobrine",
  "clfnfhex",
  "clfnfholiday",
  "clfnfhorkglorpgloop",
  "clfnfhotline",
  "clfnfhypnoslullaby",
  "clfnfimposter3",
  "clfnfimposterv4",
  "clfnfindiecross",
  "clfnfinfernalbout",
  "clfnfinfiniteirida",
  "clfnfironlung",
  "clfnfjapcreepypasta",
  "clfnfmadnesspoop",
  "clfnfmaginagematches",
  "clfnfmariomadnessdside",
  "clfnfmarioport",
  "clfnfmcmadness",
  "clfnfmidfight",
  "clfnfmiku",
  "clfnfmobmod",
  "clfnfneo",
  "clfnfpiggyfield",
  "clfnfplutoshi",
  "clfnfpokepastaperdition",
  "clfnfporifera",
  "clfnfqt",
  "clfnfremnants",
  "clfnfretrospecter",
  "clfnfrevmixed",
  "clfnfrewrite",
  "clfnfrhythmicrev",
  "clfnfrottensmoothie",
  "clfnfselfpaced",
  "clfnfshaggy4keys",
  "clfnfshaggyxmatt",
  "clfnfshucks-v2",
  "clfnfshucksv2",
  "clfnfsky",
  "clfnfsoft",
  "clfnfsohv2",
  "clfnfsonicexe",
  "clfnfsonicexe4",
  "clfnfstarlightmayhem",
  "clfnfstridentcrisis",
  "clfnftailsgetstrolled",
  "clfnftooslowfran",
  "clfnftricky",
  "clfnfTWIDDLEFINGER",
  "clfnfundertale",
  "clfnfvoid",
  "clfnfvstabi",
  "clfnfwaltenfiles",
  "clfnfwednesday-infedility",
  "clfnfwhitty",
  "clfnfzardy",
  "clfocus",
  "clfolderdungeon",
  "clfoolsmate",
  "clfootballbros",
  "clfootballlegends",
  "clforknsausage",
  "clfortunecookiegenerator",
  "clfortzone",
  "clfpa4p1",
  "clfpa4p2",
  "clfreegemas",
  "clfreerider",
  "clfreerider2",
  "clfreerider3",
  "clfridaynightfunkin",
  "clfroggerarcade",
  "clfromrusttoash",
  "clfruitninja",
  "clfunkinmix",
  "clfunnybattle",
  "clfunnybattle2",
  "clfunnymadracing",
  "clfunnyshooter2",
  "clfunnyshooter22",
  "clfuschiax",
  "clfused240",
  "clfzero",
  "clfzerox",
  "clgachaverse",
  "clGain Ground",
  "clgalaga",
  "clgameandwatchcollection",
  "clgameoflife",
  "clgamewatchgallery3",
  "clgangstabean",
  "clgangstabean2",
  "clgangsterbros",
  "clgarcello",
  "clgarfcaughtinact",
  "clgdlite",
  "clgeneralchaos",
  "clgenericfightermaybe",
  "clgeometrydashscratch",
  "clGeometryDashWave",
  "clgeometryvibes",
  "clgeorgeandtheprinter",
  "clgetawayshootout",
  "clgetontop",
  "clgettingoverit",
  "clGettothetopalthoughthereisnotop",
  "clgetyoked",
  "clggshinobi",
  "clggshinobi2",
  "clghosttrick",
  "clgimmietheairpod",
  "clgladdihoppers",
  "clglfighters",
  "clgloryhunters",
  "clglover",
  "clgo",
  "clgoalsouthafrica",
  "clgobble",
  "clgoingballs",
  "clgolddiggerfrvr",
  "clgoldenaxe",
  "clgoldenaxe2",
  "clgoldenaxe3",
  "clgoldeneye007",
  "clgoldensun",
  "clgoldensunnds",
  "clGoldenSunTheLostAge",
  "clgoldminer",
  "clgolfbattle",
  "clgolforbit",
  "clgolfsunday",
  "clgoodbigtowertinysquare",
  "clgoodbigtowertinysquare2",
  "clgoodboygalaxy",
  "clgoodmonkeymart",
  "clgooftroopsnes",
  "clgooglebaseball",
  "clgoogledino",
  "clgorescriptclassic",
  "clgorillatag",
  "clgotobed",
  "clgrandactionsimulator-ny",
  "clgranddad",
  "clgrandescapeprison",
  "clgrandshiftauto",
  "clgrandtheftautoadvance",
  "clgranny",
  "clgranny2",
  "clgranny22",
  "clgranny3",
  "clgrannycreepy",
  "clgrannynightmare",
  "clgrannyy",
  "clgranturismo",
  "clgranturismo2",
  "clgrassmowing",
  "clgravity",
  "clgravitymod",
  "clgreenergrassawaits",
  "clgrey-box-testing",
  "clgrimacebirthday",
  "clgrindcraft",
  "clgrn",
  "clgrowagarden",
  "clgrowdenio",
  "clgrowmi",
  "clgrowyourgarden",
  "clgta",
  "clgta2",
  "clgta22",
  "clgta2alt",
  "clgtaalt",
  "clgtaalty",
  "clgtachina",
  "clgtamods",
  "clguessmynumber",
  "clguesstheiranswer",
  "clgun-spin",
  "clgunblood",
  "clguncho",
  "clgunfighterjessejames",
  "clgunknight",
  "clgunmayhem",
  "clgunmayhem2",
  "clgunmayhem2goof",
  "clgunmayhemredux",
  "clgunnight",
  "clgunsmoke",
  "clgunstarheroes",
  "clgymstack",
  "clgyromite",
  "clhacx",
  "clhajimeippo",
  "clhajimenoippo",
  "clhalflife",
  "clhalloween2600",
  "clhalocombatdevolved",
  "clhandshakes",
  "clhandsofwar",
  "clhandsofwar (1)",
  "clhandsofwar(1)",
  "clhandsofwar(2)",
  "clhandulum",
  "clhanger",
  "clhanger2",
  "clhangman",
  "clhangonsms",
  "clhappyroom",
  "clhappywheels",
  "clhardwaretycoon",
  "clharmonyofdissonance",
  "clHaroldsbadday",
  "clharvestio",
  "clharvestmoon",
  "clharvestmoon2",
  "clharvestmoon64",
  "clhauntedschool",
  "clhauntthehouse",
  "clheadsoccer",
  "clheartandsoul",
  "clheartandsoul1.2.1.html",
  "clheartandsoul121",
  "clhei$t",
  "clHelios-Offline",
  "clHelios-Offline (1)",
  "clhelixjump",
  "clhellron",
  "clHelltaker",
  "clhelpnobrakes",
  "clheretic",
  "clhero3flyingrobot",
  "clherobrinereborn",
  "clhextris",
  "clHighSpeed",
  "clhighstakes",
  "clhighwayracer2",
  "clhighwaytraffic3d",
  "clhilbertcurve",
  "clhillclimbracinglite",
  "clHiNoHomo",
  "clhipsterkickball",
  "clhit8ox",
  "clhitsinglereal",
  "clhitstunfly",
  "clhl2doom",
  "clhobo",
  "clhobo2",
  "clhobo3",
  "clhobo4",
  "clhobo5",
  "clhobo6",
  "clhobo7",
  "clhobovszombies",
  "clHoennsLastWish",
  "clholebattle",
  "clholeio",
  "clhollowknight",
  "clhomesheephome",
  "clhooked",
  "clhorntale",
  "clhorrormickeymouse",
  "clhotdogbush",
  "clhotwax",
  "clhouseofhazards",
  "clhoverracerdrive",
  "clhtmlviewer",
  "clhuggywuggypixel",
  "clhumanexpenditureprogram",
  "clhungryknight",
  "clhungrylamu",
  "clhungrylamu2",
  "clhungrypumpkin",
  "clhyppersandbox",
  "clicantbelievegoogleflaggedmeforthenameofthefilelol",
  "clice age baby",
  "cliceclimber",
  "clicedodo",
  "clicefishing",
  "clicypurplehead",
  "clidlebreakout",
  "clidledice",
  "clidlefootballmanager",
  "clidleidlegamedev",
  "clidleminertycoon",
  "clidleminorzamnshes12",
  "clihateyou",
  "climageenhancer",
  "climpossiblequiz",
  "climpossiblequiz (1)",
  "climpossiblequiz2",
  "clinclementemerald",
  "clindiantrucksimiulator",
  "clinfinitecraft",
  "clinformation",
  "clinkgame",
  "clInkwell (v104)",
  "clinnkeeper",
  "clinsidestory",
  "clinsomniary",
  "clintellisphere",
  "clinteractivebuddy",
  "clinteractiveresumebuilder",
  "clinterval",
  "clintoruins",
  "clintospace",
  "clintospace2",
  "clintospace3",
  "clintothedeepweb",
  "clintrusion",
  "clip",
  "cliqball",
  "clironsnout",
  "clironsoldier",
  "clirori",
  "clitgetssolonelyhere",
  "cliwbtg",
  "cljacksmith",
  "cljacksmithencryptedorsmthn",
  "cljailbreakobbbobob",
  "cljamesbondjr",
  "cljazzjackrabbit",
  "cljazzjackrabbit2",
  "cljefflings",
  "cljellydadhero",
  "cljellydrift",
  "cljellymario",
  "cljellytruck",
  "cljellytruckgood",
  "cljetforcegemini",
  "cljetpackjoyride",
  "cljetrush",
  "cljetskiracing",
  "cljmocraft",
  "cljohnnytrigger",
  "cljohnnyupgrade",
  "cljojobaps1",
  "cljourneyarcade",
  "cljourneydownhill",
  "cljoustarcade",
  "cljsvecx",
  "cljumbomario",
  "clJUMP",
  "cljumpingshell",
  "cljunglebooksnes",
  "cljungledeerhunting",
  "cljurassicpark",
  "cljustaplatformer",
  "cljustaplatformerE",
  "cljustaplatformerE2",
  "cljustfalllol",
  "cljusthitthebutton",
  "cljusthtml",
  "cljustoneboss",
  "clkaizomarioworld",
  "clkalikan",
  "clkanyezone",
  "clkapi",
  "clkaratebros",
  "clkarlson",
  "clkartbros",
  "clKenGriffeyJrPresentsMajorLeagueBaseball",
  "clkeroseneclient",
  "clkillerinstinct",
  "clkillover",
  "clkilltheiceagebabyadventure",
  "clkimjonguntilepuzzle",
  "clkingdomheartsdays",
  "clkingdomheartsrecoded",
  "clkingdomheartsrecodedalt",
  "clkirby64",
  "clkirby64crystalshards",
  "clkirbyandtheamzingmirror",
  "clkirbycanvascurse",
  "clkirbysadventure",
  "clkirbysdreamland",
  "clkirbysdreamland3",
  "clkirbysoftandwet",
  "clkirbysqueaksquad",
  "clkirbysuperstar",
  "clkirbysuperstarultra",
  "clkirbytiltandtumble",
  "clkittencannon",
  "clklifur",
  "clknfl",
  "clknifehit",
  "clknightmaretower",
  "clknockknock",
  "clknuckleschaotix",
  "clkonkrio",
  "clkoopasrevenge",
  "clkourio",
  "clks2teams",
  "cllaceysflashgames",
  "clladnerbritishcolumbia",
  "cllastfirered",
  "cllasthorizon",
  "cllaststand",
  "cllaststand2",
  "clleaderstrike",
  "clleafblower",
  "clleapandavoid2",
  "cllearntofly",
  "cllearntofly2",
  "cllearntofly2hacked",
  "cllearntofly3",
  "clLearnToFly3Debug",
  "cllearntoflyidle",
  "cllearntoflyidlehack",
  "clLegacyOfGoku",
  "cllegionbreaker",
  "cllegobatman",
  "cllegobatman2superheroes",
  "cllegoindianajones",
  "cllegoindianajones2",
  "cllegoninjago",
  "cllegoracers",
  "cllegostarwars",
  "cllegostarwars2gba",
  "cllegostarwarsgba",
  "cllemmings",
  "clletitconsume",
  "clletsgoeevee",
  "clletsgopikachu",
  "clleveldevil",
  "clleverwarriors",
  "cllightitup",
  "cllilrunmo",
  "cllime",
  "cllinerider",
  "cllinksawakeningdx",
  "cllinktothepast",
  "cllittlealchemy2",
  "cllittlerunmo",
  "cllockthedoor",
  "clloderunner",
  "cllonewolf",
  "cllosangelesshark",
  "cllowknight",
  "clloz1",
  "cllozlinkawakening",
  "cllozminishcap",
  "cllozoracleofseasons",
  "cllozphantomhourglass",
  "cllozspirittracks",
  "clLSE",
  "cllucid",
  "clluckyblocks",
  "cllumberobby",
  "cllummm",
  "clmachrider",
  "clmadalinstuntcars",
  "clmadalinstuntcarsgood",
  "clmadalinstuntcarsmultiplayerfixed",
  "clmadden93",
  "clmadden94",
  "clmadden95",
  "clmadden96",
  "clmadden99",
  "clmaddenfootball",
  "clmaddenfootball64",
  "clmaddennfl",
  "clmaddennfl2000",
  "clmaddennfl2001",
  "clmaddennfl2002",
  "clmaddy98",
  "clmadness-retaliation",
  "clmadnessaccelerant",
  "clmadnesscombatdefense",
  "clmadnesscombatnexus",
  "clmadnessgemini",
  "clmadnesshydraulic",
  "clmadnessinteractive",
  "clmadnessoffcolor",
  "clmadnesspremediation",
  "clmadnessretaliation",
  "clmadnesss2010",
  "clmadnessstand",
  "clmadskillsmotocross2",
  "clmadstick",
  "clmadstuntcars2",
  "clmagetoweridle",
  "clmagictiles3",
  "clmagicwand",
  "clmajorasmask",
  "clmakesureitsclosed",
  "clmami",
  "clmanagod",
  "clmandelbrot",
  "clmarbleracer",
  "clmarbleracer(1)",
  "clmarchingsquares",
  "clmari0",
  "clMario Party Advance",
  "clmario3",
  "clmario64webgl",
  "clmarioandluigisuperstarsaga",
  "clmariobrosnes",
  "clmariobuilder64",
  "clmariobuilder64(1)",
  "clmariocombat",
  "clmariogolf",
  "clMarioisMissingDoneRight",
  "clmariokart64",
  "clmariokartds",
  "clmariokartsupercircuit",
  "clmariolostlevels",
  "clmariomadness",
  "clmariomakersnes",
  "clmariominusrabbids",
  "clmariopaint",
  "clmarioparty",
  "clmarioparty2",
  "clmarioparty3",
  "clmariopartyds",
  "clmariosmysterymeat",
  "clmariotennis",
  "clmariotennisgb",
  "clmariovsluigi",
  "clMarvelSuperHeroesArcade",
  "clMarvelVsCapcomPS1",
  "clMarvelVsStreetFighter",
  "clmarvelvsstreetfighterjp",
  "clmaskedforcesunlimited",
  "clmastermindworldconquerer",
  "clmatrixrampage",
  "clmattv2",
  "clmauimallard",
  "clmaxpayne",
  "clmaze",
  "clmazeescaperaycaster",
  "clmcfpsfbhd",
  "clmcraerally",
  "clmeatboy",
  "clmeatboyflash",
  "clmeatonthemove",
  "clmedalofhonor",
  "clmedievalshark",
  "clmedievil",
  "clmegacd",
  "clmegachess",
  "clmegaclient",
  "clmegaman",
  "clmegaman2",
  "clmegaman2gba",
  "clmegaman3",
  "clmegaman4",
  "clmegaman5",
  "clmegaman5gb",
  "clmegaman6",
  "clmegaman7",
  "clmegaman8",
  "clmegamanbasscftf",
  "clmegamanbattlechipchallenge",
  "clmegamanbn5tc",
  "clmegamanbn5tp",
  "clmegamanbn6cf",
  "clmegamanbn6cg",
  "clmegamanlegends",
  "clmegamanlegends2",
  "clmegamanx",
  "clmegamanx2",
  "clmegamanx3",
  "clmegamanx4",
  "clmegamanx5",
  "clmegamanx6",
  "clmegamanzero",
  "clmegamanzx",
  "clmegaminer",
  "clmelonplayground",
  "clmemorygame",
  "clmeowio",
  "clmeowuwu",
  "clmergeroundracers",
  "clmetalgear",
  "clmetalgearsolid",
  "clmetalgearsolidps",
  "clmetalslug",
  "clmetalslug2",
  "clmetalslugadvance",
  "clmetalslugmission1",
  "clmetalslugmission2",
  "clMetalSonicHyperdrive",
  "clmetroid",
  "clmetroid2",
  "clmetroidfusion",
  "clmetroidprimehunters",
  "clmetroidzeromission",
  "clmiamishark",
  "clmickeymaniasnes",
  "clmicrolife",
  "clmicromages",
  "clmidwaysgreatesthitsn64",
  "clmightyknight",
  "clmightyknight2",
  "clmimic",
  "clMinceraft-I-NotMine_V6",
  "clMinceraft-I-NotMine_V6(1)",
  "clmindmath",
  "clmindscape",
  "clmindwave",
  "clminecaves",
  "clminecraft1-8-8",
  "clminecraftcasesim",
  "clminecraftpocketedition",
  "clminecraftshooter",
  "clMINECRAFTTOWERDEFENSE",
  "clmineshooter",
  "clminesweeperplus",
  "clminhero",
  "clminicargame",
  "clminicrossword",
  "clminiflips",
  "clminimart",
  "clminishooters",
  "clminitooth",
  "clmiraginewar",
  "clmisslecommand",
  "clmk4ampedup",
  "clmkmythologiesn64",
  "clmktrilogyps1",
  "clmmbn3b",
  "clmmbn3w",
  "clmmbn4bm",
  "clmmbn4rs",
  "clmmbnws",
  "clmmsf2zxn",
  "clmmsf2zxs",
  "clmmsf3ba",
  "clmmsf3rj",
  "clmmsfd",
  "clmmsfl",
  "clmmsfp",
  "clmmwilywars",
  "clmo64",
  "clmo64(1)",
  "clmobcontrolhtml5",
  "clmobiusrevolution",
  "clMoemon Emerald Vanilla+ (v110)",
  "clmomimsleeping",
  "clmomoscrushers",
  "clmoneyrush",
  
  "clmonkeymartenc",
  "clmonsterderby",
  "clmonsterswing",
  "clmonstertracks",
  "clmonstertruckcurfew",
  "clmonstertruckportstunt",
  "clmoonemeraldextremerandomizer",
  "clmortalkombat",
  "clmortalkombat2",
  "clmortalkombat2a",
  "clmortalkombat3",
  "clmortalkombat3a",
  "clmortalkombat4",
  "clmortalkombata",
  "clmortalkombatadvance",
  "clmortkom4",
  "clmotherload",
  "clmotoroadrash",
  "clmotox3m2",
  "clmotox3m3",
  "clmotox3mm",
  "clmotox3mpoolparty",
  "clmotox3mspookyland",
  "clmotox3mwinter",
  "clmountainbikeracer",
  "clmovielist",
  "clmrdriller",
  "clmrdriller2",
  "clmrmine",
  "clmrracer",
  "clmspacman",
  "clmspacman (1)",
  "clmspacman(1)",
  "clmspacman(2)",
  "clmultitask",
  "clmutilate-a-doll",
  "clmvpbaseball",
  "clmxoffroadmaster",
  "clmyfriendpedro",
  "clmyfriendpedroarena",
  "clmyscreenresolution",
  "clmyteardrop",
  "cln",
  "clnarc",
  "clnatsuki64",
  "clnaturalselection",
  "clNautilusOS",
  "clNautilusOS(1)",
  "clNBAhangtime",
  "clNBAjam",
  "clnbajamTE",
  "clnbalive2000",
  "clnbalive2003",
  "clnblox",
  "clneonblaster",
  "clneonrider",
  "clnesworldchampion",
  "clnetattack",
  "clneverendinglegacy",
  "clnewersmbds",
  "clnewgroundsrumble",
  "clnewsuperbowserworld",
  "clnewsupermariobros",
  "clNewSuperMarioWorld2AroundtheWorld",
  "clnewyorkshark",
  "clnextdoor",
  "clnflblitz",
  "clnfscarbonowncity",
  "clnfsmostwanted",
  "clnfsporcheunleashed",
  "clnfsunderground",
  "clnfsunderground2",
  "clngon",
  "clngon(1)",
  "clnguidle",
  "clnhl2002",
  "clnhl98",
  "clnhlhitz2003",
  "clnickelodeonsuperbrawl2",
  "clNicktoonsFreezeFrameFrenzy",
  "clnightcatsurvival",
  "clnightclubshowdown",
  "clnightfire",
  "clnightshade",
  "clnikehub",
  "clnimrods",
  "clninjabrawl",
  "clninjaobbyparkor",
  "clnintendogslab",
  "clnintendoworldcup",
  "clnitclient",
  "clnitromemustdie",
  "clnomoregameasdsadfagfggdfs",
  "clnoobminer",
  "clnotyourpawn",
  "clnovaclient",
  "clnplus",
  "clnsmbuds",
  "clnsmbwds",
  "clnubbysnumberfactory",
  "clnullkevin",
  "clNutsandBoltsScrewingPuzzle",
  "clnzp",
  "clobby-99-will-lose",
  "clobby1jumpperclick",
  "clobby456",
  "clobbybike",
  "clobbycart",
  "clobbyonlyup",
  "clobbyrainbowtower",
  "clobbyslide",
  "clobbyswing",
  "clobbyyardsale",
  "clobeythegame",
  "clocarinaoftime",
  "cloddbotout",
  "cloddfuture",
  "clofflineparadise",
  "clohflip",
  "clomegalayers",
  "clomeganuggetclicker",
  "clomnipresent",
  "clonebitadventure",
  "clonenightasfreddy",
  "clonepiece",
  "clonepiecefighting",
  "cloneshotold",
  "clonlyup",
  "clonpasvg",
  "clOotMasterQuest",
  "clopenaigeneratedentry",
  "cloperius",
  "cloppositeday",
  "clopposumcountry",
  "clOrangeRoulette",
  "clorbofcreation",
  "clordinarysonicromhack",
  "cloregontrail",
  "clorgansfordebt",
  "clorigamiking",
  "clormmimastickwithclsoitcanberememberedoyeahclalienhominid",
  "clortalkombat4",
  "closu",
  "clourpleguy",
  "clouthold",
  "cloutnumbered",
  "cloutonalimb",
  "clOutrunArcade",
  "clOutrunGenesis",
  "cloverburden",
  "clovo",
  "clovo2",
  "clovodimensions",
  "clovofixed",
  "clpacman",
  "clpacmana",
  "clpacmansuperfast",
  "clpacmanworld3",
  "clpacmanworldg",
  "clpacmanworldpsx",
  "clpandameic2",
  "clpapabakeria",
  "clpapadonut",
  "clpapalouienighthunt2",
  "clpapalouiewhenburgersattack",
  "clpapalouiewhenpizzasattack",
  "clpapalouiewhensundaesattack",
  "clpapapizzagood",
  "clpapapizzagoody",
  "clpapapizzamamamia",
  "clpapasburgerIIIAAAAA",
  "clpapascheeseria",
  "clpapascupcakeria",
  "clpapasfreezeria",
  "clpapashotdoggeria",
  "clpapaspancakeria",
  "clpapaspastaria",
  "clpapasscooperia",
  "clpapassushiria",
  "clpapastacomia",
  "clpapaswingeria",
  "clpaperio",
  "clpaperio3d",
  "clpaperiomania",
  "clpapermario",
  "clPaperMarioDSE",
  "clPaperMarioPracticeHack",
  "clpapermariopromode",
  "clpapermariottyd",
  "clparappatherapper",
  "clparappatherapperalt",
  "clparkingfury",
  "clparkingfury2",
  "clparkingfury3",
  "clparkingrush",
  "clpartnersintime",
  "clpasswordchecker",
  "clpasswordgenerator",
  "clpeacekeeper",
  "clpeach",
  "clpeggle",
  "clpenaltykicks",
  "clpenguindiner",
  "clpenguinpass",
  "clpepsiman",
  "clpepsimanalt",
  "clpereelous",
  "clperfectdark",
  "clperfecthotel",
  "clpersona",
  "clpersona2",
  "clpersona2alt",
  "clpersonaalt",
  "clpetworld",
  "clphantasystar",
  "clphantasystar2",
  "clphantasystar3",
  "clphantasystar4",
  "clphasma",
  "clpheonixjusticeforall",
  "clpheonixrightaceattorny",
  "clpheonixtrialsandyear",
  "clpheonixtrialsandyeartrhfasd",
  "clpibbyapocalypse",
  "clpiclient",
  "clpico8",
  "clpico8edu",
  "clpicodriller",
  "clpicohot",
  "clpicolife",
  "clpiconightpunkin",
  "clpicosschool",
  "clpicovsbeardx",
  "clpiecesofcake",
  "clpikwip",
  "clpinballnes",
  "clpingpong",
  "clpingpongchaos",
  "clpinkbike",
  "clpinkvsunknowns",
  "clpint",
  "clpitfall",
  "clpitof100trials",
  "clpixelbattlegroundsio",
  "clpixelcombat2",
  "clpixelconvertor",
  "clpixelgun",
  "clpixelquestlostidols",
  "clpixelshooter",
  "clpixelspeedrun",
  "clpixelwarfare",
  "clpizzapapa",
  "clpizzatower",
  "clpkmnarutoans",
  "clplanetlife",
  "clplangman",
  "clplantsvszombies",
  "clplantsvszombiesnds",
  "clplatform",
  "clplazmaburst",
  "clplinko",
  "clplonky",
  "clpogo3D",
  "clpokeacademylifeforever",
  "clpokeaestheticred",
  "clpokeallin",
  "clPokeAmbrosia",
  "clpokebattlefact",
  "clpokeblack",
  "clpokeblack2alt",
  "clpokeblack2html",
  "clpokeblackalt",
  "clpokeblazeblack2redux",
  "clpokeblue",
  "clpokeclassic",
  "clpokecrown",
  "clpokecrystaladvanceredux",
  "clpokecrystalclear",
  "clpokecrystallegacy",
  "clpokediamond",
  "clpokedreamstone",
  "clpokeeliteredux",
  "clpokeelysiuma",
  "clpokeelysiumb",
  "clpokeemeraldenhanced",
  "clpokeemeraldexceeded",
  "clpokeemeraldextendedcut",
  "clpokeemeraldhorizons",
  "clpokeemeraldimperium",
  "clpokeemeraldlegacy",
  "clpokeemeraldrandom",
  "clpokeemeraldrogue",
  "clPokeEmeraldRogueEX",
  "clpokeemeraldz",
  "clpokefiregold",
  "clpokeflora",
  "clpokefrlgplus",
  "clpokefuseddimension",
  "clPokeFusion3",
  "clpokegaia",
  "clpokegoldenshield",
  "clpokegschronicles",
  "clpokeheartgold",
  "clPokeHeartgoldGenerations",
  "clpokelightplatinum",
  "clpokeliquidcrysta",
  "clpokelowbudgetcrystal",
  "clpokemegamoemon",
  "clPokemonadventurebluechapter",
  "clPokemonadventuregoldchapter",
  "clPokemonadventuregreenchapter",
  "clpokemonamnesia",
  "clPokemonbrown",
  "clpokemonclover",
  "clpokemoncrystal",
  "clPokemondbzteamtraining",
  "clpokemonemerald",
  "clpokemonemeraldcrest",
  "clpokemonemeraldimperium",
  "clpokemonemeraldkaizo",
  "clpokemonemeraldmini",
  "clPokemonemeraldrouge",
  "clPokemonemeraldrushedition",
  "clpokemonemeraldseaglass",
  "clpokemonenergizedemerald",
  "clpokemonevolvedsfdgsdfs",
  "clpokemonfirered",
  "clpokemonfireredandleafgreenplusedition",
  "clpokemonfireredrandomized",
  "clpokemongold",
  "clPokemongrape",
  "clPokemonhypnoslullaby",
  "clPokemonindianruby",
  "clpokemonkaizoironfirered",
  "clpokemonlazarus",
  "clpokemonleafgreen",
  "clPokemonleagueoflegends",
  "clPokemonletsgomewtwo",
  "clpokemonmodernemerald",
  "clpokemonmysterydungeon",
  "clpokemonperfectemerald5.5.html",
  "clpokemonperfectemerald55",
  "clPokemonpinballrubysapphire",
  "clPokemonplatinumrandomized3",
  "clpokemonquetzal",
  "clpokemonroaringred",
  "clPokemonrocketedition",
  "clpokemonruby",
  "clpokemonsaiph",
  "clpokemonsaiph2",
  "clpokemonsapphire",
  "clpokemonshinsigma",
  "clpokemonsilver",
  "clPokemonskyeproject",
  "clpokemonslgreen",
  "clpokemonsmred",
  "clpokemonsnap",
  "clPokemonsnowywhite",
  "clpokemonsors",
  "clpokemonsors2",
  "clpokemonstadium",
  "clpokemonstadium2",
  "clPokemonsunandmoonfirered",
  "clPokemonswordandshieldultimateplus",
  "clPokemontcgextension",
  "clpokemontowerdefense",
  "clPokemontradeandstache",
  "clPokemontwo",
  "clpokemonultimatefusion",
  "clpokemonunbound",
  "clpokemonvolume1",
  "clpokemonvolume2",
  "clpokemonvolume3",
  "clpokemonvolume4",
  "clPokemonyellowchapter",
  "clpokemoonemerald",
  "clpokemoongalaxy",
  "clpokemysteryexplorersofsky",
  "clpokenameless",
  "clpokeodyssey",
  "clpokepasta",
  "clpokepath",
  "clpokepearl",
  "clpokeperfectfirered",
  "clpokepicross",
  "clpokepisces",
  "clpokeplatinum",
  "clpokeplatinumrandomized",
  "clpokepureblue",
  "clpokepuregreen",
  "clpokepurered",
  "clpokerechargedpink",
  "clpokerechargedyellow",
  "clpokerecordkeepers",
  "clpokered",
  "clpokerenegadeplat",
  "clpokerocketedition",
  "clpokerowe",
  "clpokeruby",
  "clpokerunandbun",
  "clpokescorchedsilver",
  "clpokescrambledscarlet",
  "clpokesoulsilver",
  "clpokesunsky",
  "clpoketcg1",
  "clpoketcg2",
  "clpokethepit",
  "clPokeThetaEmeraldEX",
  "clpoketoomanytypes2",
  "clpoketourmaline",
  "clpokeultraviolet",
  "clpokeunovaemerald",
  "clpokevega",
  "clpokevoltwhite2redux",
  "clpokevoyager",
  "clpokewhite",
  "clpokewhite2",
  "clpokewhite2alt",
  "clpokeyellow",
  "clpokeyellowlegacy",
  "clPokémon Emerald Rush Edition (20)",
  "clPokémon Trade&_Stache (V11)",
  "clPokémon TWO (v11)",
  "clPokémonstunningsteel",
  "clpolicepursuit2",
  "clpolishedcrystal",
  "clpolytrackbutnotflagged",
  "clpolytrackbutnotflagged(1)",
  "clpolytrackworksnow",
  "clpomgetsinternet",
  "clpoorbunny",
  "clpopeyepapi",
  "clporklike",
  "clportal",
  "clportal2d",
  "clportaldefendersfastbreak",
  "clportaldefendersTD",
  "clportalflash",
  "clporter",
  "clportraitofruin",
  "clpossessquest",
  "clpostal",
  "clpotatomanseeksthetroof",
  "clpou",
  "clpou(1)",
  "clpowerslave",
  "clprankcalltungtungtungsahurclicker",
  "clpraxisfighterx",
  "clprebronzeage",
  "clprecivilationbronzeage",
  "clprehistoricshark",
  "clprestigetree",
  "clprimary",
  "clprimsmaze",
  "clprismarine",
  "clprocessortycoon",
  "clprofessorlaytonandthecuriousvillage",
  "clprowrestling",
  "clpuckman",
  "clpullfrog",
  "clpumpkinrun",
  "clpunchout",
  "clpunchthedrump",
  "clpunchthetrump",
  "clpuppethockey",
  "clpuppetmaster",
  "clpurecssstilllifewaterlemon",
  "clpushyourluck",
  "clpuyopuyofever",
  "clpvz",
  "clpvz2",
  "clpvz2gardenless",
  "clPVZM",
  "clpyrotoad",
  "clqbert",
  "clqbertarcade",
  "clqtrewired",
  "clquake",
  "clquake2",
  "clquake3",
  "clquake64",
  "clQuantumClicker",
  "clquasimono",
  "clquickieworld",
  "clqwop",
  "clracemaster3d",
  "clracingarena",
  "clradicalred",
  "clradracer",
  "clraftwars",
  "clraftwars2",
  "clragdoll-io",
  "clragdollachivement",
  "clragdollarchers",
  "clragdolldrop",
  "clragdollhit",
  "clragdollrunners",
  "clragdollsoccer",
  "clragollhit",
  "clrainbowsix",
  "clrainbowsixalt",
  "clraldiscrackhouse",
  "clrandomcolourgenerator",
  "clrandompassword",
  "clravenbase",
  "clray1",
  "clray2",
  "clrayman",
  "clraze",
  "clraze2",
  "clraze3",
  "clre3",
  "clreachthecore",
  "clreacticore",
  "clrealflightsim",
  "clrebuild",
  "clrebuild2",
  "clrecoil",
  "clredalert",
  "clredball",
  "clredball2",
  "clredball3",
  "clredball4",
  "clredball4(1)",
  "clredball4vol2",
  "clredball4vol3",
  "clredhanded",
  "clredtierunner",
  "clredvbluefix",
  "clredvsblue2",
  "clredvsbluewar",
  "clreignofcentipede",
  "clrenegades",
  "clrepobad",
  "clresidentevil",
  "clresidentevil2",
  "clresidentevil2d1",
  "clresidentevil2d2",
  "clresizer",
  "clresortempire",
  "clretrobowl",
  "clretrobowlcollege",
  "clretrohighway",
  "clretropingpong",
  "clreturnman",
  "clreturnman2",
  "clreturntoriddleschool",
  "clrevolutionidle",
  "clrewrite2",
  "clrh",
  "clrhythmheaven",
  "clrhythymymheaven",
  "clricochetkills2",
  "clriddle",
  "clriddlemiddleschool",
  "clriddleschool",
  "clriddleschool2",
  "clriddleschool3",
  "clriddleschool445544444$$444$444",
  "clriddletransfer",
  "clriddletransfer2",
  "clriddleuneversityfix",
  "clridgeracer",
  "clringloader",
  "clripples",
  "clrisehigher",
  "clriskystakes",
  "clristar",
  "clroadfighter",
  "clroadoffury",
  "clroadofthedead",
  "clroadofthedead2",
  "clroadrunnernes",
  "clrocketgoalio",
  "clrocketjump",
  "clrocketknight2",
  "clrocketknight2 (1)",
  "clrocketknight2(1)",
  "clrocketknight2(2)",
  "clrocketknightadventures",
  "clrocketleague",
  "clrocketpult",
  "clrocketsoccerderby",
  "clrodha",
  "clroguesoul",
  "clroguesoul2",
  "clrollerballer",
  "clrollingsky",
  "clrollyvortex",
  "clrolypolymonster",
  "clrooftoprun",
  "clrooftopsnipers",
  "clrooftopsnipers2",
  "clroomclicker",
  "clrosegold",
  "clrotate",
  "clroulettehero",
  "clrouletteknight",
  "clruffle",
  "clrun",
  "clrun-2",
  "clrun2",
  "clrun3",
  "clrunfromwitheredfox",
  "clrunningfred",
  "clrussianbuckshot",
  "clrussiancardriver",
  "clrussiansandbox",
  "clsaihatestation",
  "clsandboxcity",
  "clsandboxels",
  "clsandsofthecoliseum",
  "clsandstone",
  "clsandstone(1)",
  "clsandtris",
  "clsantarun",
  "clsanty",
  "clsaszombieassault2",
  "clsatryn",
  "clsattyam",
  "clsaulgoodmanrun",
  "clsausageflip",
  "clsayorisnotebook",
  "clscalethedepths",
  "clScamptonTheGreatFightRecreate",
  "clscarletandviolet",
  "clscarletshift",
  "clscarymazegame",
  "clscaryshawarma",
  "clscaryteacher3d",
  "clschoolboyrunaway",
  "clscoobydoocreepyrun",
  "clscoobydoozombiehunter",
  "clscrapmetal3",
  "clscrapyarddog",
  "clscratchoptions",
  "clscribblenauts",
  "clscubabear",
  "clsd-thewar",
  "clsdf",
  "clseamongrel",
  "clsecretofmana",
  "clsega2gg",
  "clSegaSonicTheHedgehog",
  "clself",
  "clsentryfortress",
  "clserenitrove",
  "clserioussamadvance",
  "clservingupmadness",
  "clsevendays",
  "clsfk",
  "clsfk2",
  "clsfklaststand",
  "clsfkleague",
  "clshadowcourier",
  "clshadowdancer",
  "clshadowdancersecret",
  "clshaggy",
  "clshaggy (1)",
  "clshantaegb",
  "clshapedodgefrenzy",
  "clshapetransform",
  "clshc1",
  "clshc2",
  "clshc3",
  "clshift",
  "clshift2",
  "clshift3",
  "clshiftatmidnight",
  "clshinmegamitenseidevilsurvivor",
  "clshinobi",
  "clshinobi3",
  "clshinobirevenge",
  "clshoppingcarthero",
  "clshortlife",
  "clshotout4",
  "clshredmill",
  "clshredsauce",
  "clshrek-2",
  "clshrubnaut",
  "clshwultimatem",
  "clsideeffects",
  "clsidepocket",
  "clsidhumoosewalatributepage",
  "clsierra7",
  "clsignuppage",
  "clsilenthill",
  "clsilenthillalt",
  "clsilk",
  "clsilkmelody",
  "clsilkwormlifecycle",
  "clsiloshowdow",
  "clsilver",
  "clsimcity64",
  "clsimongame",
  "clsimplecounter",
  "clsimpsonsarcade",
  "clSINGLEFILE",
  "clsixwaystodie",
  "clskateit",
  "clskateordie",
  "clskibididibidygyattohiorizzingallovertheplacestillwatermangotheoryfemboydrool",
  "clskibidiinthebackrooms",
  "clskibidishooter",
  "clskinwalker",
  "clskong",
  "clskyrace-3d",
  "clSkyRiders",
  "clskywire",
  "clskywire2",
  "clslalomnes",
  "clslenderman",
  "clslendytubbies",
  "clsliceitall",
  "clslicemaster",
  "clslideinthewoods",
  "clslimelabratory",
  "clslipways",
  "clslitherio",
  "clslope",
  "clslope2player",
  "clslope3",
  "clslopeplus",
  "clslotornot",
  "clslowroads",
  "clsm63redux",
  "clsm64greenstars",
  "clsm64hiddenstars",
  "clSM64Land",
  "clsm64lastimpact",
  "clsm64liminaldream",
  "clsm64oot",
  "clsm64sapphire",
  "clsm64yscaled",
  "clsmadvance2",
  "clsmadvance3",
  "clSmash Hit Ripoff",
  "clsmashkarts",
  "clsmashkartsworking",
  "clsmashremix",
  "clsmashremix2.0.1.html",
  "clsmashremix201",
  "clsmb12",
  "clsmbc",
  "clsmbcrossover",
  "clsmbgameover",
  "clsmbremastered",
  "clsmc",
  "clsmgds",
  "clsnailbob",
  "clsnailbob2",
  "clsnailbob3",
  "clsnailbob4space",
  "clsnailbob5lovestory",
  "clsnakegame",
  "clsnakeis",
  "clsnakelike",
  "clsnipershot",
  "clsniperv2",
  "clsnowballio",
  "clsnowboardobby",
  "clsnowbros",
  "clsnowbros (1)",
  "clsnowbros(1)",
  "clsnowbros(2)",
  "clSnowBrosGenesis",
  "clsnowbrothers",
  "clsnowdrift",
  "clsnowrid",
  "clsnowrideee",
  "clsnowrider",
  "clsnowridergoodygumdrops",
  "clsnowriderrrr",
  "clsnowroad",
  "clsnowwhite",
  "clsoccerbros",
  "clsoccernes",
  "clsoccerrandom",
  "clsoccerrandomgood",
  "clsodasimulator",
  "clsolarsandbox",
  "clsolarsmash",
  "clsolarsystem",
  "clsolatrobo",
  "clsolitaire",
  "clsolstice",
  "clsomari64",
  "clSonic & Knuckles + Sonic The Hedgehog 3",
  "clsonic1contemporary",
  "clsonic1mobile",
  "clSonic1ScoreRush",
  "clSonic1TheSuperChallenges",
  "clsonic2mobile",
  "clsonic2pinkedition",
  "clSonic2ScoreRush",
  "clsonic2timeandplace",
  "clsonic3andknuckles",
  "clsonic3andsally",
  "clsonic3complete",
  "clsonic3dblast",
  "clsonic3dblastdx",
  "clsonicadvance",
  "clsonicadvance2",
  "clsonicadvance2sp",
  "clsonicadvance3",
  "clsonicandashuro",
  "clsonicandfallingstar",
  "clsonicandknuckles",
  "clsonicbattle",
  "clsonicblast",
  "clsoniccd",
  "clsoniccdmobile",
  "clsonicchaos",
  "clsonicclassiccollection",
  "clsonicclassicheroes",
  "clsonicclassicheroes(1)",
  "clSonicClassics",
  "clsoniccolors",
  "clsonicdeltaorigins",
  "clsonicdrift",
  "clsonicdrift2",
  "clsoniceexeog",
  "clsonicerazor",
  "clsonicgg",
  "clSonicHellfireSaga",
  "clSonicInSM64",
  "clSonicinSMW",
  "clSonicinSMW(1)",
  "clsonicinsmw(2)",
  "clsonicjam",
  "clsoniclabyrinth",
  "clsonicmania",
  "clsonicmaniaplus",
  "clsonicmegamix",
  "clsonicmegamix5.0aLEAKED.html",
  "clsonicmon",
  "clsonicmushroomblast",
  "clsonicpocketadventure",
  "clsonicr",
  "clsonicralt",
  "clsonicrevert",
  "clsonicrush",
  "clsonicrushadventure",
  "clsonicscorchedquest",
  "clsonicspinball",
  "clsonicthehedgehog",
  "clsonicthehedgehog2",
  "clsonicthehedgehog3",
  "clsonny2",
  "clsortthecourt",
  "clsotn",
  "clsouljumper",
  "clsoundboard",
  "clsouthparkn64",
  "clSovereignoftheskys",
  "clspacebarclicker",
  "clspacecompany",
  "clspaceharriersms",
  "clspaceinvade95",
  "clspaceinvaders",
  "clspaceiskey",
  "clspaceiskey2",
  "clspaceiskeyxmas",
  "clspacewarsbattleground",
  "clspacewaves",
  "clspecialmission",
  "clspeedperclick",
  "clspeedstars",
  "clspelunky",
  "clspewer",
  "clspidermanps1",
  "clspiralroll",
  "clspiritsofhell",
  "clSpongebobPowerKartGrandPrix",
  "clSportsHeadsIceHockey",
  "clsprinter",
  "clsprunked",
  "clsprunki",
  "clsprunkiclicker",
  "clsprunkipyramixed",
  "clspyhunter",
  "clsquidplayground",
  "clSSF2Arcade",
  "clSSF2TArcade",
  "clstackballio",
  "clstacktris",
  "clstackydash",
  "clstarfox",
  "clstarfox2",
  "clstarfox64",
  "clstarfoxsfx2",
  "clstarraiders",
  "clstateio",
  "clstation141",
  "clstationmeltdown",
  "clstationsaturn",
  "clsteakandjake",
  "clstealbrainrot",
  "clstealbrainrotonline",
  "clstealthassassin",
  "clstealthmaster",
  "clsteelempire",
  "clsteelsurge",
  "clsteepdescent",
  "clstickarchersbattle",
  "clstickdefenders",
  "clstickfighter",
  "clstickjetchallenge",
  "clstickmanandguns",
  "clstickmanclash",
  "clstickmanduel",
  "clstickmangtacity",
  "clstickmanhook",
  "clStickmanKingdomclash",
  "clstickmankombat2d",
  "clstickmanstealingdiamond",
  "clstickmerge",
  "clstickminairship",
  "clstickminbreakingbank",
  "clstickminescapingprison",
  "clstickminfleecomplex",
  "clstickrpgcomplete",
  "clstickslasher",
  "clstickwar",
  "clstickwar2",
  "clstickwithit",
  "clstopwatch",
  "clstormthehouse",
  "clstormthehouse2",
  "clstormthehouse3",
  "clstrangeinsults",
  "clstrangejournet",
  "clstreangeropepolice",
  "clStreetFighter1Arcade",
  "clstreetfighter2",
  "clStreetFighter2Arcade",
  "clStreetFighter2CEArcade",
  "clStreetFighter2HFArcade",
  "clStreetFighter2HFArcade(1)",
  "clstreetfighter2turbo",
  "clstreetfighteralpha3",
  "clstreetfighterumuhsomething",
  "clstreetofrage",
  "clstreetofrage2",
  "clstreetofrage3",
  "clstrikeforceheroes",
  "clstrikeforceheroes2",
  "clstrikeforceheroes3",
  "clstrikerdummies",
  "clstylesavvy",
  "clsubwaysurfersbarcelona",
  "clsubwaysurfersbeijing",
  "clsubwaysurfersberlin",
  "clsubwaysurfersbuenosaires",
  "clsubwaysurfershavana",
  "clsubwaysurfershouston",
  "clsubwaysurfersiceland",
  "clsubwaysurferslondon",
  "clsubwaysurfersmexico",
  "clsubwaysurfersmiami",
  "clsubwaysurfersmonaco",
  "clsubwaysurfersneworeleans",
  "clsubwaysurfersneworleans",
  "clsubwaysurferssanfrancisco",
  "clsubwaysurferssanfrancisco (1)",
  "clsubwaysurferssanfrancisco(1)",
  "clsubwaysurfersstpetersburg",
  "clsubwaysurferswinterholiday",
  "clsubwaysurferszurich",
  "clsugarsugar",
  "clsugaryspire",
  "clsuika",
  "clsuikapico",
  "clsummerrider",
  "clsunandmoon",
  "clsuperbomberman",
  "clsuperbomberman2",
  "clsuperbomberman3",
  "clsuperbomberman4",
  "clsuperbomberman5",
  "clsuperc",
  "clsupercarrush",
  "clsupercastlevaniaVI",
  "clsuperchibiknight",
  "clsupercold",
  "clsuperdarkdeception",
  "clsuperdiagonalmario2",
  "clsuperdromebugs",
  "clsuperdromebugs(1)",
  "clsuperfallingfred",
  "clsuperfighters",
  "clsuperhot",
  "clsuperhotlinemiami",
  "clsuperhouseofdeadninjas",
  "clsuperislandadventure",
  "clsuperliquidsoccer",
  "clsupermario",
  "clsupermario3mix",
  "clsupermario63",
  "clsupermario64",
  "clsupermario64ds",
  "clsupermario74",
  "clsupermarioallstars",
  "clsupermariobros",
  "clsupermariobros2",
  "clsupermariobros2us",
  "clsupermariobros3",
  "clsupermariobros3real",
  "clsupermariokart",
  "clsupermarioland",
  "clsupermarioland2",
  "clsupermarioland2dx",
  "clsupermariolanddx",
  "clsupermariomon",
  "clsupermariorpg",
  "clsupermariostarroad",
  "clsupermariostarroadretooled",
  "clsupermariosunshine64",
  "clsupermarioworld",
  "clsupermarioworld2",
  "clSuperMarioWorldThe SecretOfThe7GoldenStatues",
  "clsupermetroid",
  "clsupermonkeyballjr",
  "clsupernoahsark3D",
  "clsuperoliverworld",
  "clsuperonionboy2",
  "clsuperpickleballadventure",
  "clsuperpunchout",
  "clSuperPunchOutEN",
  "clsuperpuzzlefighter2turbo",
  "clsuperpuzzlefighter2turboalt",
  "clsupersantakicker",
  "clsupersantakicker2",
  "clsuperscribblenauts",
  "clsupersmashbros",
  "clsupersmashflash",
  "clsupersmashflash08",
  "clsupersmashflash2",
  "clsupersmashflash2butdifversion",
  "clsuperstreetfighter2turbojp",
  "clsupertiltbros",
  "clsupitdept",
  "clsupremeduelist",
  "clSupremeDuelist2019",
  "clsurvivalracev2",
  "clsurvivorio",
  "clsushicat",
  "clsushicat2",
  "clsushiunroll",
  "clswerve",
  "clswingforbrainrots",
  "clswitch",
  "clswitchblade",
  "clswordandshieldultimateplus",
  "clswordfight",
  "clswordplay",
  "clswordsandsandals",
  "clswordsandsandals2",
  "clswordsandsouls",
  "clsydneyshark",
  "cltabi",
  "cltabletanks",
  "cltabletennisworldtour",
  "cltacostand",
  "cltag-",
  "cltagc3",
  "cltagcm",
  "clTaikonoTatsujin",
  "cltailofthedragon",
  "cltailsadventure",
  "cltailsskypatrol",
  "cltaisei",
  "cltakeover",
  "cltallio",
  "cltallmanrun",
  "cltankmayhem",
  "cltankpixel",
  "cltanktrouble",
  "cltanukisunset",
  "cltanukisunsetuhhhhhhhh",
  "cltapper",
  "cltaproad",
  "cltasklistapp",
  "cltastyplanet",
  "cltboidemo",
  "cltboilambeternal",
  "cltechnicaldoc",
  "cltecmobowl",
  "cltekken2ps1",
  "cltekken3ps1",
  "cltelephonetrouble",
  "cltelocation",
  "cltempest2000",
  "cltempleofboom",
  "cltemplerun2",
  "cltempoverdose",
  "cltennisnes",
  "clteod",
  "clterminal",
  "clterra",
  "clterritorialio",
  "clterritorywar",
  "clterritorywar2",
  "clterritorywar3",
  "cltetris",
  "cltetrisattack",
  "cltetrisgba",
  "cltetrisgrandmaster2",
  "clthanksforremindingmeihadtofixthis",
  "cltheclassroom",
  "cltheclassroom2",
  "cltheclassroom3",
  "clthedeadseat",
  "clthedeepestsleep",
  "clthedude",
  "cltheenchantedcave2",
  "cltheimpossiblegame",
  "cltheincrediblemachine",
  "clthelaststand",
  "clthelaststandunioncity",
  "clthelaststandunioncity (1)",
  "clTheLoneRanger",
  "clthemaninthewindow",
  "clthemepark",
  "clthemeparkpsx",
  "clthepit",
  "clthereisnofile",
  "clthermomorph",
  "clthesodorrace",
  "clTheSunForTheVampire",
  "cltheyarecoming",
  "clthisistheonlylevel",
  "clthisistheonlylevel2",
  "clthisistheonlyleveltoo",
  "clthreegoblets",
  "clthrowapotato",
  "clthrowapotatoagain",
  "clthwack",
  "cltiberiandawn",
  "cltictactoe",
  "cltiles",
  "cltimeshooter2",
  "cltimeshooter3",
  "cltimewarriors",
  "cltinyfishing",
  "cltipscalculator",
  "cltmnt",
  "cltmnt2arc",
  "cltmntarc",
  "cltmntturtlesintime",
  "cltoastarling",
  "cltoasterball",
  "cltodolist",
  "cltoejam&earl",
  "cltoejam&earlpof",
  "cltombofthemass",
  "cltommorowandyesterday",
  "cltomodachicollection",
  "cltonyhawkskater2",
  "cltonyhawkskater4",
  "cltonyhawksunderground",
  "cltoomanytypes",
  "cltopspeedracing3d",
  "cltosstheturtle",
  "cltotm",
  "cltouhou",
  "cltouhou2",
  "cltouhou3",
  "cltouhou4",
  "cltouhou5",
  "cltowerblocks",
  "cltowercrash3d",
  "cltowerwizard",
  "cltownscraper",
  "cltrace",
  "cltrafficjam3d",
  "cltrafficracer",
  "cltralalerotralalaescapetungtungtungsahur",
  "cltrappedwithjester",
  "cltrapthecat",
  "cltrechoroustrials",
  "cltrechoroustrialspart2",
  "cltreeshateyou",
  "cltrexrunner",
  "cltriachnid",
  "cltripleplay2000",
  "cltriviacrack",
  "cltrollfacequest1",
  "cltrollfacequest10",
  "cltrollfacequest11",
  "cltrollfacequest12",
  "cltrollfacequest13",
  "cltrollfacequest2",
  "cltrollfacequest3",
  "cltrollfacequest4",
  "cltrollfacequest5",
  "cltrollfacequest6",
  "cltrollfacequest7",
  "cltrollfacequest8",
  "cltrollfacequest9",
  "cltrucksim",
  "cltsuzukimaze",
  "cltubejumpers",
  "cltungtungbasics",
  "cltungtunghorror",
  "cltungtungtungsahurobby",
  "cltunnelrush",
  "cltunnelrushbetter",
  "cltupertariotros",
  "clturbostars",
  "clturokdinosaurhunter",
  "cltwinshot",
  "cltwinshot (1)",
  "cltwinshot(1)",
  "cltwistedmetal",
  "cltwistedmetal2",
  "cltwoball3d",
  "clucds",
  "cluckyblockobbyEUOPHRATESRIVER",
  "cludhavsudoku",
  "clufoswampoddysey",
  "clultima",
  "clultimateassassian2",
  "clultimateassassian3",
  "clUltimatecardrivingsimulator",
  "clultimatemortalkombat",
  "clultimatemortalkombat3",
  "clultrakill",
  "clumjammerlammy",
  "clumstickmangameidkiforgor",
  "cluncannycatgolf",
  "clunderneath",
  "clundertalelb",
  "clundertaler",
  "clundertaleyellow",
  "clunfairmario",
  "clunfairmarioworkquestionmark",
  "clunfairundyne",
  "clunicyclehero",
  "clunitresdreams",
  "cluno",
  "clunownking",
  "cluntime",
  "cluntitledgoosegame",
  "clupgradecomplete",
  "clupgradecomplete2",
  "clupslash",
  "clurbanchampion",
  "clusterrush",
  "clUvuvwevwevweOnyetenvewveUgwemubwemOssas",
  "clUZG",
  "clvampiresurvivors",
  "clvanguard",
  "clvaportrails",
  "clvex",
  "clvex2",
  "clvex3",
  "clvex3xmas",
  "clvex4",
  "clvex5",
  "clvex6",
  "clvex7",
  "clvex8",
  "clvexchallenges",
  "clvexx3m",
  "clvexx3m2",
  "clvibribbon",
  "clvillager",
  "clvincentmansionofthedead",
  "clvisitor",
  "clvolleyball",
  "clvolleyrandom",
  "clvollyballchallenge",
  "clvortex",
  "clvsagore",
  "clvsnonsense",
  "clVSSMB",
  "clvvvvvv",
  "clvvvvvv(1)",
  "clwackyflip",
  "clwaluigitacostand",
  "clwarfare1917",
  "clwarfare1944",
  "clwargames",
  "clwarioland1",
  "clwarioland3",
  "clwarioland4",
  "clwariowarediy",
  "clwariowareinc",
  "clwariowaretouched",
  "clwartheknight",
  "clwatermelonpixel",
  "clwaterpoolio",
  "clwaterworks",
  "clwavedash",
  "clwaverace64",
  "clwaverun",
  "clwbml",
  "clwebdashers",
  "clwebecomewhatwebehold",
  "clwebfishing",
  "clwebmine",
  "clweltling",
  "clwermhole",
  "clwhackamole",
  "clwhackthetheif",
  "clwhackyourboss",
  "clwhackyourcomputer",
  "clwhatamarioworld",
  "clwheeliebike",
  "clwheely",
  "clwheely2",
  "clwheely3",
  "clwheely4",
  "clwheely5",
  "clwheely6",
  "clwheely7",
  "clwheely8",
  "clwilywars",
  "clwindowsdoors",
  "clwinterfalling",
  "clwinterolympics",
  "clwipeout2097",
  "clwipeout2097alt",
  "clwitchcrafttd",
  "clwolfchild",
  "clwolfenstein",
  "clwolfenstein3d",
  "clwonderboy3",
  "clwonderboyarcade",
  "clwoodworm",
  "clWordGuesserGame",
  "clwordle",
  "clworldcup98",
  "clworldshardestgame",
  "clworldshardestgame2",
  "clworldshardestgame3",
  "clworldshardestgame4",
  "clwpnfire",
  "clwrassling",
  "clwreckingcrew",
  "clwrestlebros",
  "clwwfattitude",
  "clwwfsmackdown2",
  "clxevent",
  "clXevious",
  "clxmenarcade",
  "clXMenChildrenOfTheAtomArcade",
  "clXMenVSStreetFighter",
  "clxor",
  "clyanderesimulator",
  "clyarsrevenge",
  "clyellow",
  "clyohohoio",
  "clYoshisStrangeQuest",
  "clyouarelucky",
  "clyourturntodie",
  "clyouvs100skibidi",
  "clyumenikki",
  "clzdoom",
  "clzelda2thelegendoflink",
  "clZeldaIndigoch2",
  "clzeldaminishcap",
  "clzenword",
  "clzoinkz",
  "clzombieexploder",
  "clzombieroad",
  "clzombierush",
  "clzombiesatemyneighboors",
  "clzombopaclypse2",
  "clzombotron",
  "clzombotron2",
  "clzombotronreboot",
  "clzrist",
  "clzuma",
  "clzumashooter",
  "clÖoo",
  "clʘ",
  "codeorg",
  "esm",
  "geometry-swallow",
  "npm",
  "skypack",
  "supremeduelistfix",
  "thiefpuzzle",
];
function generateAllSections() {
  try {
    document.getElementById("lolbutton").remove();
  } catch (e) {}
  const allChars = [
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",
  ];

 const MAINTENANCE_GAMES = new Set(["cl3dpinballspacecadet","cl500calibercontractz","cladventurecapitalist","clangrybirds2","clantarttycoon","claviamasters","claviamastersbuggy","clbabysniperinvietnam","clbadparenting","clbaldi-3","clbaldisfunnewschoolultimate","clbeachboxingsim","clbearsus","clbendrowned","clbergentruck201x","clBFDIBranches","clbitburner","clblackjackhhhh","clblockcraftshooter","clblockydemolitionderby","clblood","clbouncybasketball","clbrawlsimulator3d","clbreadskate","clcarrampvspolicechase","clcarstuntsdriving","clcheeserolling","clclassof09","clcommandandconquer","clcookieclickercool","clcookieclickermodmenu","clcyberbungracing","clDashmetry","cldecision3","cldemolitionderbycrashracing","cldiredecks","cldodecadragons","cldontyoulecturemehtml","cldoom2dDOS","cldoom2dos","clducklifebattle","clducklingsio","cldukenukem2","cldukenukem3d","cldungeonraid","cldungeonsanddegenerategamblerdebug","cldungeonsanddegenerategamblers","cleagleride","cleggycar","clelasticface","clemujs","clescaperoad3","clfancypantsadventure3","clfearassessment","clfivenightsatepsteins","clfnaw","clfnfdocumictxtv3","clfnfrewrite","clfnfstarlightmayhem","clfreegemas","clfuschiax","clgachaverse","clGeometryDashWave","clgetyoked","clglfighters","clgoingballs","clgolforbit","clgorillatag","clgranny2","clgrowdenio","clhacx","clheretic","clhero3flyingrobot","clhooked","clhyppersandbox","clice age baby","cljetskiracing","cljustaplatformerE2","clkanyezone","clkilltheiceagebabyadventure","clkimjonguntilepuzzle","clkirbysoftandwet","clkourio","cllaststand","cllegionbreaker","cllittlerunmo","cllonewolf","clmakesureitsclosed","clmariominusrabbids","clmightyknight2","clminesweeperplus","clminhero","clminimart","clmotox3mwinter","clmyteardrop","clnimrods","clnullkevin","clNutsandBoltsScrewingPuzzle","clonebitadventure","clpetworld","clpint","clPokémon Emerald Rush Edition (20)","clprestigetree","clprismarine","clprocessortycoon","clpumpkinrun","clquake","clquake3","clracingarena","clraldiscrackhouse","clredvsblue2","clredvsbluewar","clretrobowl","clrisehigher","clroadofthedead","clrocketgoalio","clruffle","clsaulgoodmanrun","clschoolboyrunaway","clsd-thewar","clshiftatmidnight","clsideeffects","clsilk","clslopeplus","clsnipershot","clsniperv2","clspacewarsbattleground","clspiralroll","clstationsaturn","clsteepdescent","clstickmanclash","clstickmerge","clstickminairship","clstickminfleecomplex","clstrikerdummies","clsuperchibiknight","clsuperhot","clsuperliquidsoccer","clsuperonionboy2","clsupitdept","clSupremeDuelist2019","cltagcm","cltaisei","clthedude","cltheyarecoming","cltimewarriors","cltopspeedracing3d","cltrace","cltreeshateyou","cltungtungtungsahurobby","clultima","clundertalelb","clundertaler","cluntime","cluntitledgoosegame","clUvuvwevwevweOnyetenvewveUgwemubwemOssas","clvex3","clvincentmansionofthedead","clvortex","clwaterpoolio","clwheeliebike","clyouvs100skibidi","clzdoom","clzombopaclypse2","supremeduelistfix"]);

const SAVE_BAR_SCRIPT = `(function () {
    var SKIP_DBS = { "UnityCache": 1 };

    function collectLocalStorage() {
        var data = {};
        for (var i = 0; i < localStorage.length; i++) {
            var k = localStorage.key(i);
            data[k] = localStorage.getItem(k);
        }
        return data;
    }

    function b64FromBytes(bytes) {
        var bin = "";
        var CH = 0x8000;
        for (var i = 0; i < bytes.length; i += CH) {
            bin += String.fromCharCode.apply(null, bytes.subarray(i, i + CH));
        }
        return btoa(bin);
    }

    function bytesFromB64(b64) {
        var bin = atob(b64);
        var bytes = new Uint8Array(bin.length);
        for (var i = 0; i < bin.length; i++) {
            bytes[i] = bin.charCodeAt(i);
        }
        return bytes;
    }

    function encValue(v, depth) {
        depth = depth || 0;
        if (depth > 12) { return { t: "p", v: null }; }
        if (v === undefined) { return { t: "un" }; }
        if (v === null) { return { t: "p", v: null }; }
        var ty = typeof v;
        if (ty !== "object") { return { t: "p", v: v }; }
        if (v instanceof Date) { return { t: "d", v: v.getTime() }; }
        if (v instanceof ArrayBuffer) { return { t: "ab", v: b64FromBytes(new Uint8Array(v)) }; }
        if (ArrayBuffer.isView(v)) {
            return { t: "ta", n: v.constructor.name, v: b64FromBytes(new Uint8Array(v.buffer, v.byteOffset, v.byteLength)) };
        }
        if (Array.isArray(v)) {
            return { t: "arr", v: v.map(function (x) { return encValue(x, depth + 1); }) };
        }
        var proto = Object.getPrototypeOf(v);
        if (proto === Object.prototype || proto === null) {
            var out = {};
            Object.keys(v).forEach(function (k) {
                out[k] = encValue(v[k], depth + 1);
            });
            return { t: "obj", v: out };
        }
        return { t: "p", v: String(v) };
    }

    function decValue(e) {
        if (!e || typeof e !== "object" || !e.t) { return e; }
        var bytes, T;
        switch (e.t) {
            case "p": return e.v;
            case "un": return undefined;
            case "d": return new Date(e.v);
            case "ab":
                bytes = bytesFromB64(e.v);
                return bytes.buffer;
            case "ta":
                T = window[e.n] || Uint8Array;
                return new T(bytesFromB64(e.v));
            case "arr": return (e.v || []).map(decValue);
            case "obj":
                var o = {};
                Object.keys(e.v || {}).forEach(function (k) {
                    o[k] = decValue(e.v[k]);
                });
                return o;
            default: return e.v;
        }
    }

    function dumpDatabase(info, cb) {
        var req;
        try { req = indexedDB.open(info.name); }
        catch (e) { cb(null); return; }
        req.onsuccess = function () {
            var db = req.result;
            var dump = { version: db.version, stores: {} };
            var names = Array.prototype.slice.call(db.objectStoreNames);
            var left = names.length;
            function finish() {
                try { db.close(); } catch (e) {}
                cb(dump);
            }
            if (!left) { finish(); return; }
            names.forEach(function (sn) {
                var meta = { keyPath: null, autoIncrement: false, items: [] };
                try {
                    var store = db.transaction(sn, "readonly").objectStore(sn);
                    meta.keyPath = store.keyPath;
                    meta.autoIncrement = store.autoIncrement;
                    var cursorReq = store.openCursor();
                    cursorReq.onsuccess = function (ev) {
                        var cur = ev.target.result;
                        if (cur) {
                            meta.items.push([encValue(cur.key), encValue(cur.value)]);
                            cur.continue();
                        } else {
                            dump.stores[sn] = meta;
                            left--;
                            if (!left) finish();
                        }
                    };
                    cursorReq.onerror = function () {
                        dump.stores[sn] = meta;
                        left--;
                        if (!left) finish();
                    };
                } catch (e) {
                    dump.stores[sn] = meta;
                    left--;
                    if (!left) finish();
                }
            });
        };
        req.onerror = function () { cb(null); };
        req.onblocked = function () { cb(null); };
    }

    function collectIndexedDB(cb) {
        var out = {};
        if (!indexedDB || !indexedDB.databases) { cb(out); return; }
        indexedDB.databases().then(function (dbs) {
            var list = (dbs || []).filter(function (info) { return !SKIP_DBS[info.name]; });
            var left = list.length;
            if (!left) { cb(out); return; }
            list.forEach(function (info) {
                dumpDatabase(info, function (dump) {
                    if (dump) { out[info.name] = dump; }
                    left--;
                    if (!left) cb(out);
                });
            });
        }).catch(function () { cb(out); });
    }

    function restoreDatabase(name, dump, cb) {
        var req = indexedDB.open(name, dump.version || 1);
        req.onupgradeneeded = function (ev) {
            var db = ev.target.result;
            Object.keys(dump.stores).forEach(function (sn) {
                if (!db.objectStoreNames.contains(sn)) {
                    var meta = dump.stores[sn];
                    try {
                        db.createObjectStore(sn, { keyPath: meta.keyPath || null, autoIncrement: !!meta.autoIncrement });
                    } catch (e) {
                        try { db.createObjectStore(sn); } catch (e2) {}
                    }
                }
            });
        };
        req.onsuccess = function (ev) {
            var db = ev.target.result;
            var names = Object.keys(dump.stores).filter(function (sn) {
                return db.objectStoreNames.contains(sn) && dump.stores[sn] && dump.stores[sn].items;
            });
            if (!names.length) { db.close(); cb(); return; }
            try {
                var tx = db.transaction(names, "readwrite");
                names.forEach(function (sn) {
                    var st = tx.objectStore(sn);
                    dump.stores[sn].items.forEach(function (pair) {
                        var val = decValue(pair[1]);
                        var key = decValue(pair[0]);
                        try { st.put(val, key); }
                        catch (e) { try { st.put(val); } catch (e2) {} }
                    });
                });
                tx.oncomplete = function () { db.close(); cb(); };
                tx.onerror = function () { db.close(); cb(); };
                tx.onabort = function () { db.close(); cb(); };
            } catch (e) {
                try { db.close(); } catch (e2) {}
                cb();
            }
        };
        req.onerror = function () { cb(); };
        req.onblocked = function () { cb(); };
    }

    function downloadSaves() {
        collectIndexedDB(function (idb) {
            var payload = {
                app: "UGS",
                exported: new Date().toISOString(),
                localStorage: collectLocalStorage(),
                indexedDB: idb
            };
            var blob = new Blob([JSON.stringify(payload)], { type: "application/json" });
            var a = document.createElement("a");
            a.href = URL.createObjectURL(blob);
            a.download = "ugs-saves-" + payload.exported.slice(0, 10) + ".json";
            document.documentElement.appendChild(a);
            a.click();
            setTimeout(function () { a.remove(); URL.revokeObjectURL(a.href); }, 5000);
        });
    }

    function loadSaves(file) {
        var reader = new FileReader();
        reader.onload = function () {
            var payload;
            try { payload = JSON.parse(reader.result); }
            catch (e) { alert("That file is not a valid save file."); return; }
            if (!payload || payload.app !== "UGS" || typeof payload.localStorage !== "object") {
                alert("That file is not a UGS save file.");
                return;
            }
            var keys = Object.keys(payload.localStorage || {});
            keys.forEach(function (k) {
                try { localStorage.setItem(k, payload.localStorage[k]); } catch (e) {}
            });
            var idbNames = Object.keys(payload.indexedDB || {});
            var left = idbNames.length;
            function done() {
                alert("Save file loaded (" + keys.length + " local entries). Reload the game to see your progress.");
            }
            if (!left) { done(); return; }
            idbNames.forEach(function (nm) {
                restoreDatabase(nm, payload.indexedDB[nm], function () {
                    left--;
                    if (!left) done();
                });
            });
        };
        reader.readAsText(file);
    }

    var CSS = "#ugs-savebar-handle{position:fixed;top:10px;right:10px;z-index:2147483647;background:rgba(12,14,20,0.85);color:#7ec8ff;font-family:sans-serif;font-weight:bold;font-size:10px;letter-spacing:1.5px;padding:8px 10px;border-radius:8px;border:1px solid rgba(126,200,255,0.4);cursor:pointer;opacity:0.14;transition:opacity 0.3s;user-select:none;-webkit-user-select:none}"
        + "#ugs-savebar-handle:hover{opacity:1}"
        + "#ugs-savebar-handle.ugs-on{opacity:1}"
        + "#ugs-savebar-panel{position:fixed;top:46px;right:10px;z-index:2147483647;display:none;flex-direction:column;gap:6px;background:rgba(12,14,20,0.92);border:1px solid rgba(126,200,255,0.3);border-radius:10px;padding:10px;font-family:sans-serif}"
        + "#ugs-savebar-panel.ugs-open{display:flex}"
        + "#ugs-savebar-panel button{background:#2456a0;color:#fff;border:none;border-radius:6px;padding:9px 12px;font-family:sans-serif;font-size:12px;font-weight:600;cursor:pointer;width:140px}"
        + "#ugs-savebar-panel button:hover{background:#316fbf}";

    var handle = null, panel = null, panelTimer = null;

    function hidePanel() {
        if (panel) { panel.classList.remove("ugs-open"); }
        if (handle) { handle.classList.remove("ugs-on"); }
    }

    function showPanel() {
        if (!panel) { return; }
        panel.classList.add("ugs-open");
        if (handle) { handle.classList.add("ugs-on"); }
        clearTimeout(panelTimer);
        panelTimer = setTimeout(hidePanel, 20000);
    }

    function mkButton(label, cb) {
        var b = document.createElement("button");
        b.type = "button";
        b.textContent = label;
        b.addEventListener("click",
  "clislander",
  "clsurvevio", cb);
        return b;
    }

    function buildUI() {
        var st = document.createElement("style");
        st.textContent = CSS;
        document.documentElement.appendChild(st);

        handle = document.createElement("div");
        handle.id = "ugs-savebar-handle";
        handle.title = "Save files";
        handle.textContent = "SAVE";
        handle.addEventListener("click", function () {
            if (panel && panel.classList.contains("ugs-open")) { hidePanel(); } else { showPanel(); }
        });

        panel = document.createElement("div");
        panel.id = "ugs-savebar-panel";

        var fileInput = document.createElement("input");
        fileInput.type = "file";
        fileInput.accept = "application/json,.json";
        fileInput.style.display = "none";

        panel.appendChild(mkButton("download save file", downloadSaves));
        panel.appendChild(mkButton("load save file", function () { fileInput.click(); }));
        panel.appendChild(mkButton("close", hidePanel));
        panel.appendChild(fileInput);

        fileInput.addEventListener("change", function () {
            var f = fileInput.files && fileInput.files[0];
            if (f) { loadSaves(f); }
            fileInput.value = "";
        });

        document.documentElement.appendChild(handle);
        document.documentElement.appendChild(panel);

        handle.classList.add("ugs-on");
        setTimeout(function () { handle.classList.remove("ugs-on"); }, 5000);

        document.addEventListener("click", function (ev) {
            if (!panel || !panel.classList.contains("ugs-open")) { return; }
            if (ev.target === handle || panel.contains(ev.target)) { return; }
            hidePanel();
        }, true);

        document.addEventListener("fullscreenchange", function () {
            var host = document.fullscreenElement || document.documentElement;
            host.appendChild(handle);
            host.appendChild(panel);
        });
    }

    function init() {
        try { buildUI(); }
        catch (e) { /* never break the game */ }
    }

    if (document.readyState === "loading") {
        document.addEventListener("DOMContentLoaded", init);
    } else {
        init();
    }

})();`;
const SAVE_BAR_TAG = "<script>" + SAVE_BAR_SCRIPT + "<\/script>";

  const filesByChar = {};
  allChars.forEach((char) => {
    filesByChar[char] = [];
  });

  files.forEach((file) => {
const lower = file.toLowerCase();
  const base = lower.startsWith("cl") ? lower.substring(2) : lower;
  if (base.length > 0) {
    const lead = (base[0].normalize("NFD").replace(/\p{M}/gu, "")[0]) || base[0];
  const firstChar = lead.toUpperCase();
    if (filesByChar[firstChar]) {
      filesByChar[firstChar].push(file);
    }
  }
  });

  const container = document.getElementById("sections-container");
  allChars.forEach((char) => {
    const section = document.createElement("div");
    section.className = "letter-section";
    section.id = `section-${char}`;

    const header = document.createElement("div");
    header.className = "letter-header";
    header.textContent = char;
    section.appendChild(header);

    const buttonsContainer = document.createElement("div");
    buttonsContainer.className = "buttons-container";

    if (filesByChar[char].length > 0) {
      filesByChar[char].forEach((file) => {
        const btn = document.createElement("input");
        btn.type = "button";
        btn.value = MAINTENANCE_GAMES.has(file) ? file + " (maintenance)" : file;
        btn.onclick = () => {
          function normalizeFileName(name) {
            if (/\.html?$/i.test(name)) return name;
            return name + ".html";
          }

          const normalized = normalizeFileName(file);
          const encoded = encodeURIComponent(normalized);
          const cacheBust = Date.now();

          // Try our own copy first (works when self-hosted, or once the
          // GitHub account is publicly visible again), then fall back to
          // live mirrors so games always load.
          const sources = [
            `UGS-Files/${encoded}?t=${cacheBust}`,
            `https://cdn.jsdelivr.net/gh/yeodaienkyle-afk/ugs-singlefile@main/UGS-Files/${encoded}?t=${cacheBust}`,
            `https://cdn.jsdelivr.net/gh/lipama/ugs-singlefile/UGS-Files/${encoded}?t=${cacheBust}`,
            `https://cdn.jsdelivr.net/gh/bubbls/ugs-singlefile/UGS-Files/${encoded}?t=${cacheBust}`,
            `https://raw.githubusercontent.com/lipama/ugs-singlefile/main/UGS-Files/${encoded}?t=${cacheBust}`,
          ];

          // Open during the click event. Opening after fetch resolves is blocked
          // by most browsers because the user gesture has already ended.
          const newWin = window.open("about:blank", "_blank");
          if (!newWin) {
            alert("Allow pop-ups for this page to open games.");
            return;
          }
          newWin.document.write("<p>Loading " + normalized.replace(/[&<>"']/g, "") + "...</p>");
          newWin.document.close();

          function trySource(i) {
            if (i >= sources.length) {
              newWin.document.open();
              newWin.document.write("<p>Couldn't load this game from any source. Check your connection and try again.</p>");
              newWin.document.close();
              return;
            }
            fetch(sources[i])
              .then((response) => {
                if (!response.ok) throw new Error(response.status);
                return response.text();
              })
              .then((text) => {
                // document.write on about:blank otherwise resolves relative game
                // assets against the launcher, not the fetched game's folder.
                const gameUrl = new URL(sources[i], document.baseURI);
                const baseHref = new URL(".", gameUrl).href;
                const baseTag = '<base href="' + baseHref.replace(/&/g, "&amp;").replace(/"/g, "&quot;") + '">';
                if (!/<base\b/i.test(text)) {
                  if (/<head\b[^>]*>/i.test(text)) {
                    text = text.replace(/<head\b[^>]*>/i, (head) => head + baseTag);
                  } else if (/<html\b[^>]*>/i.test(text)) {
                    text = text.replace(/<html\b[^>]*>/i, (html) => html + "<head>" + baseTag + "</head>");
                  } else {
                    text = text.replace(/^(\s*<!doctype[^>]*>\s*)?/i, (doctype) => doctype + "<head>" + baseTag + "</head>");
                  }
                }
if (/<head\b[^>]*>/i.test(text)) {
                  text = text.replace(/<head\b[^>]*>/i, (h) => h + SAVE_BAR_TAG);
                } else if (/<html\b[^>]*>/i.test(text)) {
                  text = text.replace(/<html\b[^>]*>/i, (h) => h + "<head>" + SAVE_BAR_TAG + "</head>");
                } else {
                  text = text.replace(/^(\s*<!doctype[^>]*>\s*)?/i, (d) => d + SAVE_BAR_TAG);
                }
                newWin.document.open();
                newWin.document.write(text);
                newWin.document.close();
              })
              .catch(() => trySource(i + 1));
          }
          trySource(0);
        };
        btn.style.width = "100%";
        btn.style.height = "100%";
        buttonsContainer.appendChild(btn);
      });
    } else {
      section.classList.add("empty");
      const emptyMsg = document.createElement("div");
      emptyMsg.className = "empty-message";
      emptyMsg.textContent = "No files";
      buttonsContainer.appendChild(emptyMsg);
    }

    section.appendChild(buttonsContainer);
    container.appendChild(section);
  });

  generateSidebar(allChars, filesByChar);
}

function generateSidebar(allChars, filesByChar) {
  const sidebar = document.getElementById("sidebar");

  allChars.forEach((char) => {
    const btn = document.createElement("button");
    btn.className = "sidebar-btn";
    btn.textContent = char;

    if (filesByChar[char].length === 0) {
      btn.classList.add("empty");
    } else {
      btn.onclick = () => {
        const section = document.getElementById(`section-${char}`);
        if (section) {
          section.scrollIntoView({
            behavior: "smooth",
            block: "start",
          });
        }
      };
    }

    sidebar.appendChild(btn);
  });
}
generateAllSections();
